### ISSUE TITLE
cds-icon and dropdown text doesn't have any space in between

### ISSUE THREAD

**Issue by YunjunWang** [vmware-clarity/ng-clarity#1016]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support channel in slack to raise Clarity issues._**

## Describe the bug

When using Clarity 15 to create a dropdown ui with cds-icon, there's no space btw the dropdown button text and the cds-icon if you've size specified e.g. size-"14"

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to 'https://stackblitz.com/edit/clarity-dark-theme-clr15-4dwdvg'
2.  Check the space between the dropdown text and cds-icon
3.  There's no space in between

## Expected behavior

Always have proper space (padding/margin) between the dropdown button text and cds-icon used for the dropdown

## Versions

**Clarity version:**

- [ ] v15.x

**Framework version:**

_ie: Angular 15_

**Device:**

- Type: [e.g. MacBook]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by pawaru** [comment]
This seems to have been addressed in v16. Kindly check this Stackblitz:
https://stackblitz.com/edit/clarity-dark-theme-clr16-pwuf1h

v15 Screenshot:
![image](https://github.com/vmware-clarity/ng-clarity/assets/137300110/1f0359fc-0c26-494b-b091-68e0d7bfed13)

v16 Screenshot:
![image](https://github.com/vmware-clarity/ng-clarity/assets/137300110/7c519b88-898c-44f4-bc2c-77daff8165ee)
