### ISSUE TITLE
Angular Wizard component shows vertical scroll bars

### ISSUE THREAD

**Issue by ygoron** [vmware-clarity/ng-clarity#107]
Angular Wizard component shows vertical scroll bars. The issue is reproducible  by using link from the documentation: https://angular.clarity.design/documentation/wizards#examples. Seems to be reproducible in Windows environment only. Mac OSX works fine.

Windows (Chrome):
![Screen Shot 2022-05-06 at 2 26 04 PM](https://user-images.githubusercontent.com/4013029/167196929-3c2dd2cc-a914-4920-8a20-1ac209c91cb0.png)
MacOSX (Chrome):
![image](https://user-images.githubusercontent.com/4013029/167197048-014491e5-85ee-4a8a-83a6-f3cf5299a1a2.png)

**Comment by SamiSkalli** [comment]
Additionally, the modal body doesn't take 100% of the modal width. Is there a way to manually fix this in my code ? This can be seen in the documentation as well.

**Comment by larsk27** [comment]
Next to that there's always this vertical scrollbar, after update to newest clarity version, there's no horizontal scrollbar when the content is too large. Before it was possible to scroll...

![2022-05-27_11-43-38](https://user-images.githubusercontent.com/37844639/170675245-9bd3221b-a8b6-460b-b25b-38726cd618f9.jpg)

**Comment by ashleyryan** [comment]
this is mostly fixed, but now there's a new occasionally scroll bar issue where the modal content isn't stretching all of the available space and rendering a scroll bar and smaller than expected div

**Comment by larsk27** [comment]
> this is mostly fixed, but now there's a new occasionally scroll bar issue where the modal content isn't stretching all of the available space and rendering a scroll bar and smaller than expected div

Yes, definitly in Version 4, but I think also in Version 5.

**Comment by larsk27** [comment]
> @larsk27 do you know when you last had the horizontal scrollbar?
> 
> I have a fix open for the original issue, but not that one (yet): #251

@ashleyryan Was definitly working in Version 4, I think also in Version 5 but there I'm not 100% sure.
