### ISSUE TITLE
Buttons using a clrLoading directive have the button text faded-in on page load

### ISSUE THREAD

**Issue by wokis** [vmware-clarity/ng-clarity#1075]
## Describe the bug

Buttons using a `clrLoading` directive have the button text faded-in on page load. Buttons without the directive do not.

![7B01511B-5E3E-4B61-9A50-C2B1467DACE2](https://github.com/vmware-clarity/ng-clarity/assets/4148643/7c9e19f9-1bb0-43cb-842b-9349d0569d52)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr16-wbbydf

1.  Observe the buttons on page load/reload

## Expected behavior

Buttons using a `clrLoading` directive should not have button text faded-in on page load.

## Versions

**Clarity version:**

- [ ] v15.x
- [x] v16.x
- [ ] Other:

**Framework version:**

Angular 16

**Device:**

- Type: PC
- OS: Windows 10
- Browser: Chrome
- Version: 119

**Comment by kevinbuhmann** [comment]
Thank you for reporting this bug. I have opened a PR to resolve this issue!
