### ISSUE TITLE
Separator Alignment off in DataGrid

### ISSUE THREAD

**Issue by shahabh3003** [vmware-clarity/ng-clarity#108]
## Describe the bug

The vertical alignment of separators for header row and data rows differs by one pixel. Have a look at the attached screenshot.

<img width="609" alt="Screenshot 2022-05-11 at 1 32 41 AM" src="https://user-images.githubusercontent.com/98009279/167712628-5687ec11-2d86-4897-bcae-6be1599675ee.png">

## How to reproduce

1.  Go to [Datagrid](https://angular.clarity.design/documentation/datagrid/selection)
2.  Scroll down to grid and See error.

## Expected behavior

<img width="609" alt="Screenshot 2022-05-11 at 1 32 00 AM" src="https://user-images.githubusercontent.com/98009279/167712557-910588d2-cb16-4923-93c5-3ad0c36d0b88.png">

## Versions

**Clarity version:**

- [x] v12.x
- [ ] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:** Angular 12

**Device:**

- Type: MacBook
- OS: iOS
- Browser: chrome, safari

**Comment by Jinnie** [comment]
There are 2 ways for this to get fixed. Move the header separator (actually all of them) one pixel to the left, or move the row cell separators one pixel to the right.
We need design input what will be the better approach here and if this constitutes a visual breaking change which will need to be merged with a major version update.

**Comment by shahabh3003** [comment]
By when should we expect the next major update release?

**Comment by kevinbuhmann** [comment]
I believe this has since been fixed. I don't see this misalignment in v15 or v16.

https://storybook.clarity.design/?path=/story/datagrid-datagrid--default&args=multiSelectable:true
https://v15.storybook.clarity.design/?path=/story/datagrid-datagrid--default&args=multiSelectable:true
