### ISSUE TITLE
Observe inconsistency with the node's selection rectangle size in the tree view with ellipsis for nodes text 

### ISSUE THREAD

**Issue by vundev** [vmware-clarity/ng-clarity#109]
This is a bug report for the `@clr` Angular or UI versions of the design system.

Prerequisites:
* We have a clr tree inside a div container with **max-width** set.
* Each node is represented by a html button which uses ellipsis for its text just to decrease the total width of the tree when we have deeply nested configurations.

[Stackblitz](https://stackblitz.com/edit/clr-recursive-tree-bjuz8z?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.component.html,src%2Fapp%2Ftree.ts,angular.json).

Steps to reproduce the behaviour:

1.  Create the tree with the described requirements
2.  When you click or hover on each tree node then the selection rectangle does not reach the tree's right border. Also some
strange horizontal scroll bars appear for part of the nodes.

I expect no scroll bars to appear per node, just only one for the whole tree because it exceeds the max size of its div container and also the selection rectangle to reach the tree's right border.

**Clarity version:**

- [x] v12.x
- [x] v13.x
- [x] Other: 5

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: MacBook pro
- OS: macOS
- Browser chrome
- Version 96

**Comment by vundev** [comment]
![Screenshot 2022-05-11 at 11 00 29](https://user-images.githubusercontent.com/219103/167799959-34ac90c2-dc8e-4eeb-8aee-3ace531521a6.png)

**Comment by bbogdanov** [comment]
Hi @vundev,

[Stackblitz example](https://stackblitz.com/edit/clr-recursive-tree-bjuz8z?file=src%2Fapp%2Fapp.component.scss)

Lines 9-12

We will discuss it in the team if this should be the default behaviour but until then use the CSS workaround.

**Comment by kevinbuhmann** [comment]
>I expect no scroll bars to appear per node, just only one for the whole tree because it exceeds the max size of its div container and also the selection rectangle to reach the tree's right border

Both issues appear to be fixed in v16: https://stackblitz.com/edit/clarity-dark-theme-clr16-15wq4w
