### ISSUE TITLE
css properties are getting overwritten when we use avi-data-grid inside  avi-collection-data-grid.

### ISSUE THREAD

**Issue by kmanideep00** [vmware-clarity/ng-clarity#110]
### All the below issues are related to this scenario

<img width="1449" alt="Screenshot 2022-05-11 at 5 31 52 PM" src="https://user-images.githubusercontent.com/99945451/167845326-3109df9e-8f35-4b85-903a-56d7811d133a.png">

### Describe the bug:
There is no separator between Name and Checkbox in Header section of avi-data-grid

<img width="372" alt="Screenshot 2022-05-11 at 4 09 19 PM" src="https://user-images.githubusercontent.com/99945451/167831189-12eea7a8-f3be-4f03-9279-3e86668e851e.png">

### How to reproduce:

**Steps to reproduce the behaviour:**

1. Implement avi-data-grid inside each row of avi-collection-data-grid
2. Inside avi-data-grid you can observe there is no separator between checkbox and name

### Expected behaviour:

<img width="356" alt="Screenshot 2022-05-11 at 4 15 49 PM" src="https://user-images.githubusercontent.com/99945451/167832068-249b92d3-475d-4c24-b320-6a4650846b5a.png">

### Describe the bug:

The vertical alignment of seperator in header section is changed.

<img width="356" alt="Screenshot 2022-05-11 at 4 18 41 PM" src="https://user-images.githubusercontent.com/99945451/167832513-d5d01d8e-77f5-4231-a706-c508b28cb63c.png">

### How to reproduce:

**Steps to reproduce the behaviour:**

1. Implement avi-data-grid inside each row of avi-collection-data-grid
2. Inside avi-data-grid you can observe the alignment

### Expected behaviour:

<img width="356" alt="Screenshot 2022-05-11 at 4 21 25 PM" src="https://user-images.githubusercontent.com/99945451/167832933-cbdf48e5-8f53-4563-9c28-752f5bd31194.png">

### Describe the bug:

The data inside avi-data-grid are not aligned at centre vertically.

<img width="1408" alt="Screenshot 2022-05-11 at 4 24 15 PM" src="https://user-images.githubusercontent.com/99945451/167833486-f775224b-8dce-47b6-85fb-d475d8bdaffe.png">

### How to reproduce:

**Steps to reproduce the behaviour:**

1. Implement avi-data-grid inside each row of avi-collection-data-grid
2. Inside avi-data-grid you can observe the data

### Expected behaviour:

<img width="1408" alt="Screenshot 2022-05-11 at 4 26 39 PM" src="https://user-images.githubusercontent.com/99945451/167833788-e5931920-30ed-4b2c-85a0-a80ceff0f534.png">

### Describe the bug:

Checkbox of rows of avi-data-grid are getting highlighted when we are just hovering over the rows of avi-collection-grid.

https://user-images.githubusercontent.com/99945451/167835101-4456be73-fd72-4523-a480-2515a81c324a.mov

### How to reproduce:

**Steps to reproduce the behaviour:**

1. Implement the avi-collection-data-grid
2. Hover over the row of avi-collection-data-grid and you can observe that checkbox of rows of avi-data-grid are highlighted.

### Expected behaviour:

1. When we hover over the row of avi-collection-data-grid checkbox of rows of avi-data-grid should not be highlighted.
2. They should get highlighted only when rows of avi-data-grid are hovered.

**Comment by ashleyryan** [comment]
What is avi data grid? Can you create a stackblitz example?

**Comment by Jinnie** [comment]
Closing as stale. Even if it was not, I don't think we want to support nesting grids of any kind, as seen on the demo. This leads to huge accessibility problems.
A datagrid should not be used for layout purposes, it's a _data_-grid.
