### ISSUE TITLE
Wizard: Cannot initialize a wizard with asynchronous pages

### ISSUE THREAD

**Issue by znpopov** [vmware-clarity/ng-clarity#1108]
## Describe the bug

When you try to create a ClrWizard and set the pages asynchronously, the following error is thrown:

`ERROR TypeError: Cannot read properties of null (reading 'pageTitle')`

This regression was introduced with the following PR: https://github.com/vmware-clarity/ng-clarity/pull/640

## How to reproduce

Broken workflow: https://stackblitz.com/edit/clarity-dark-theme-clr16-kfpomv?file=src%2Fapp%2Fapp.component.html

1.  Click "Open Wizard with pending pages" button.

## Expected behavior

Working workflow: https://stackblitz.com/edit/clarity-dark-theme-clr15-xlmhw7?file=src%2Fapp%2Fapp.component.html

## Versions

**Clarity version:**

- [ X] v15.x
- [ X] v16.x
- [ X] Other: main

## Additional notes

There is another general issue for this error: https://github.com/vmware-clarity/ng-clarity/issues/813
I opened this one for a particular valid user workflow.

Please fix this issue on main, 16.x and 15.x release lines. Thanks!

**Comment by kevinbuhmann** [comment]
Wizards with missing pages are not supported. This may have happened to work before, but it was never supported to have a wizard open with zero pages. I would suggest loading your wizard pages before opening/rendering the wizard.
