### ISSUE TITLE
Problems with DatePicker when used in a datagrid filter

### ISSUE THREAD

**Issue by itaneva** [vmware-clarity/ng-clarity#111]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

I want to implement a custom date filter for clarity datagrid. It should be a simplified version of this one: https://www.ag-grid.com/angular-data-grid/filter-date/  . There are two major problems:
1. The positioning of controls - the date-picker goes behind the filter.
2. When date-picker handles a date selection event, the filter is closed.

I am using clarity @clr/angular version 12.0.8

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-q7hhkh?file=src/app/date-filter.ts

## Expected behavior

The date picker works fine when embedded in a dialog. I expect a similar behavior.

## Versions

**Clarity version:**

- [ ] v12.x

**Framework:**
- [ ] Angular

**Framework version:**
 Angular 12.1.3

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
We have several scenarios where the different types of overlays don't work well when nested in each other.
The hard z-index values we use are breaking a lot of the possible flexibility.
I'll try to pinpoint as much as possible from these scenarios and provide a fix for all of them.
