### ISSUE TITLE
Impossible to build light full standalone web-component with Angular + Clarity

### ISSUE THREAD

**Issue by Rebolon** [vmware-clarity/ng-clarity#1111]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support channel in slack to raise Clarity issues._**

## Describe the bug

I try to build a web component that will be used in legacy application (not angular application) that uses its own legacy css.
When i build the component, it always embed all Clarity CSS whereas i want to import only required CSS, and Fonts are not embeded

## How to reproduce

I build a sample in this repository : https://github.com/Rebolon/angular-clarity-webcomponent-for-stackoverflow-and-vmware-github
It wrap the clr-alert to provide a custom my-alert. It's in the projects/webcomponent. No CSS are embeded in angular.json. You can see the result by 
1. clone [doing ](https://github.com/Rebolon/angular-clarity-webcomponent-for-stackoverflow-and-vmware-github)
2. npm install
3. ng serve --project webcomponent
4. 4. open localhost:4200

The alert is displayed after a short delay and the original CSS are not modified (look at the input and the button), but 
 * the fonts are not the one from Clarity : the text of the alert is not the good one
 * the size of the main.js is too heavy because it embed all clr-ui.min.css

I tried other way that can be reproduced by installing `npm i http-server` and running http-serve in folder http-server/case-1 (style not applied whereas main.js is 1,5Mb) and http-server/case-2 (style applied from main window but produce side-effect on all the window html)

## Expected behavior

Building web component should produce a standalone component usable in legacy application with only required css that doesn't produce any side effects to main window.

## Versions

**Clarity version:**

- [x] v16.x

**Framework version:**

Angular 17

**Device:**

any

## Additional notes

/

**Comment by kevinbuhmann** [comment]
Our [web component library](https://github.com/vmware-clarity/core) might be a better choice for this.

**Comment by Rebolon** [comment]
Indeed the web component library doesn't have all components : 
 * for an alert (which is only for the demo) there is only clr-alert, no cds-alert
 * in our use case, we use dropdown and dropdown and dropdown-menu, and once again, only angular has a component. 
Maybe i'm wrong and i didn't found the related web-component.

**Comment by kevinbuhmann** [comment]
Currently, our styles are in a single global stylesheet. In your reproduction, you are importing the entire `clr-ui.min.css` and encapsulating it in shadow DOM. That is not going to work well because it's a global stylesheet and not designed to be in shadow DOM.

Unfortunately, our Angular components are not designed to be used in this way. We don't have any plans to isolate our styles by component for use in shadow DOM. I'm sorry, but this is just something we don't support and don't plan to support.
