### ISSUE TITLE
https://angular.clarity.design/documentation  for v13 not working

### ISSUE THREAD

**Issue by Aleksander-Dorkov** [vmware-clarity/ng-clarity#113]
This bug if for the website ONLY not the framework.

## Describe the bug
When ever you go to https://angular.clarity.design/documentation  and select the documentation for v13 you get 404.
 I am assuming that clarity supports angular 13  and the 13 refers to angular 13 

## How to reproduce
Got to https://angular.clarity.design/documentation and click
[Example](https://i.ibb.co/3k2Xq45/Screenshot-2022-05-12-140209.png)

You should get 404
[Result](https://i.ibb.co/dmfBKJh/Untitled.png)

**Comment by Jinnie** [comment]
The 404 error is no more, probably fixed while fixing a temporary 404 error for the v12 website.
An issue remains with the version indicator, which still shows "Version 12" on the "angular.clarity.design" website, which actually displays the content for the "Version 13".
Leaving this open until we fix the version indicator.
