### ISSUE TITLE
Multi-select combobox does not clear input after selecting an item

### ISSUE THREAD

**Issue by macguirerintoul** [vmware-clarity/ng-clarity#1177]
## Describe the bug

When typing to search for an item in a multi-select combobox, then pressing enter to select the item, the partially-typed item is not cleared, requiring the user to manually clear the input before searching for another item. 

## How to reproduce

The issue can be reproduced on the [Clarity site](https://clarity.design/documentation/combobox/code), or in the [Storybook](https://storybook.clarity.design/?path=/story/combobox-combobox--default&args=clrMulti:true).

1.  Go to a multi-select combobox
2.  Partially type the name of an item
3. Select the item using enter
5. See the partially-typed item is still in the combobox, until it is blurred

## Expected behavior

After selecting an item, the input is cleared so the user can begin searching for another item.

See [Polaris combobox](https://polaris.shopify.com/components/selection-and-input/combobox?example=combobox-with-multi-select), [Vaadin combobox](https://vaadin.com/docs/latest/components/multi-select-combo-box), [Paste combobox](https://paste.twilio.design/components/multiselect-combobox)

## Versions

**Clarity version:**

- [x] v15.x
- [x] v16.x
- [ ] Other:

**Framework version:**

Angular 16

**Device:**

- Type: MacBook Pro 16,2
- OS: macOS 14.2.1 (23C71)
- Browser: Chrome 
- Version: 121.0.6167.85 (Official Build) (x86_64)

**Comment by dtsanevmw** [comment]
Hello,

Thanks for the feedback. Currently this can't be described as bug because it was intentional but I reported it internally and we are going to take it in mind. 

Regards,
Daniel Tsanev
