### ISSUE TITLE
ng add schematics not working

### ISSUE THREAD

**Issue by robertIsaac** [vmware-clarity/ng-clarity#120]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

schematics not working

## How to reproduce

run `ng add @clr/angular
`
## Expected behavior

the command to work

## Versions

**Clarity version:**

- [ ] v12.x
- [x] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

**Device:**

- Type: MacBook Pro
- OS: MacOS
- Version: 12.4

## Additional notes

error logs
```
ℹ Using package manager: npm
✔ Found compatible package version: @clr/angular@13.3.0.
✔ Package information loaded.

The package @clr/angular@13.3.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

**Comment by steve-haar** [comment]
Due to resource and time constraints, the ng add schematics was never moved over from the old repo and is currently not supported.

**Comment by boeckMt** [comment]
> https://angular.clarity.design/documentation/get-started is updated. I removed the `ng add` instructions and updated the core package name.

I think `@webcomponents/webcomponentsjs` is missing in the command `npm install @cds/core @clr/icons @clr/angular @clr/ui --save`

**Comment by kevinbuhmann** [comment]
We don't current support schematics. The instructions on the website no longer reference the `ng add` or `ng update` commands.
