### ISSUE TITLE
regression in clr-tree component in clarity16

### ISSUE THREAD

**Issue by vinayvivekananda** [vmware-clarity/ng-clarity#1263]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support channel in slack to raise Clarity issues._**

## Describe the bug
When we have some custom components in clr-tree-node, layout is broken. Tree node height is not adjusted according to content.

## How to reproduce

Working in clarity 15 -->  https://stackblitz.com/edit/clarity-light-theme-clr15-mexuof?file=src%2Fapp%2Fapp.component.html

Broken in clarity 16 --> https://stackblitz.com/edit/clarity-light-theme-clr16-vpd3pr?file=src%2Fapp%2Fapp.component.html

1. Load the clarity 16 from stackblitz link above
2. Check how <ul> is rendered.
3. 

## Expected behavior

<ul> should be rendered as in clarity 15 stackblitz link

## Versions

**Clarity version:**

- [x] 16.3.2

**Framework version:**
Angular 16.2.12

**Device:**
MacBook Pro, Mac OS Sonoma 14.3.1 Chrome 121.0.6167.184

## Additional notes

_Add any other notes about the problem here._

**Comment by williamernest** [comment]
Thanks for submitting this issue, this was resolved with v16.3.6. 
https://github.com/vmware-clarity/ng-clarity/releases/tag/v16.3.6
