### ISSUE TITLE
Core 6.0 causes big icons

### ISSUE THREAD

**Issue by rbirkgit** [vmware-clarity/ng-clarity#138]
## Describe the bug

Using Clarity Core 6.0 causes icons in menus, buttons etc to be 20px instead of 16px

## How to reproduce

Use Core 6.0 (instead of 5.x) and _not using_ Core style sheets.

1. View min-height of icons in collapsed navigation

(v5) https://stackblitz.com/edit/clarity-v13-core-v5-icons
(v6) https://stackblitz.com/edit/clarity-v13-core-v6-icon

## Expected behavior

Icons remain 16px with Core 6.0

## Versions

**Clarity version:**

- [x] v12.x
- [x] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

## Additional notes

Including Core styles fixes the issue, but Angular apps should not need to include them. In the mean time we have downgraded to Core 5.7.2 in all our apps.

**Comment by rbirkgit** [comment]
Seems the icon default size changed from:
`var(--cds-global-space-7,calc((16 / var(--cds-global-base,20)) * 1rem))`
to:
`var(--cds-global-space-7,1rem)`

**Comment by rbirkgit** [comment]
Just want to make sure this fixes buttons / butt bars too and not just the vertical menu. Asking as the fix only changes the vertical menu scss.

**Comment by ashleyryan** [comment]
I'm looking into a fix in Core that I think will address this more broadly, but you're right that this only fixes the vertical nav. Let me look into button icons as well.
