### ISSUE TITLE
Error when press enter in combobox

### ISSUE THREAD

**Issue by tienthanhjlw** [vmware-clarity/ng-clarity#1382]
## Describe the bug

While focusing in the input of a combobox, if the selection list is not open. When you press enter, the button's click handler function will be called.

## How to reproduce

1. Focus commbobox
2. Press `enter`

```html
<form clrForm clrLayout="vertical">
  <button (click)="handleClick($event)">Click Me</button>
  <clr-combobox [(ngModel)]="vertical.one" name="one" required [disabled]="disabled" aria-label="one" class="foo">
    <clr-options>
      <clr-option clrValue="1" id="custom-id-1">1</clr-option>
      <clr-option clrValue="2">2</clr-option>
      <clr-option clrValue="3">3</clr-option>
    </clr-options>
  </clr-combobox>
</form>
```

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**Clarity version:**

- [x] v13.x
- [x] v15.x
- [x] Other:

**Framework version:**
_ie: Angular 13, 15_

**Device:**

- Browser [e.g. chrome]

**Comment by kevinbuhmann** [comment]
Isn't this normal HTML form behavior? When enter is pressed with an input is focused, the submit button is activated by the browser. Try making the button `type="button"` instead. (Buttons are submit buttons by default.)

**Comment by tienthanhjlw** [comment]
oh thanks you so much! Sorry for the lack of understanding
