### ISSUE TITLE
Regression in Datagrid Manage columns

### ISSUE THREAD

**Issue by kumart-netapp** [vmware-clarity/ng-clarity#1418]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support space in Google Chat to raise Clarity issues._**

## Describe the bug
After upgrading the clarity to v16.5.0, we  are seeing the default hidden columns headers are showing and misplacing the rows data and creating confusion.

## How to reproduce
Issue can be seen from official Clarity component docs demo: https://v16.clarity.design/documentation/datagrid/code/hide-show

Below are the exact steps(gif):

![clarity_dg_hiddencolumnBug](https://github.com/vmware-clarity/ng-clarity/assets/85227867/98d3dc97-a14a-4288-a92e-d63eb357472d)

## Expected behavior
Should not show the hidden header by default.

## Versions

**Clarity version:**

- [ x] v16.5.0

**Framework version:**
Angular 16.2.12

**Device:**

- Type: [e.g. MacBook]
- OS: Windows 11
- Browser Chrome
- Version 125

## Additional notes

_Add any other notes about the problem here._

**Comment by kumart-netapp** [comment]
When can we expect the fix for 16.x release?

**Comment by 4nt1m0n** [comment]
When can we expect the 17.x release?

**Comment by dtsanevmw** [comment]
We just released today!
