### ISSUE TITLE
Datagrid filter input field lose focus

### ISSUE THREAD

**Issue by ArturSobieraj** [vmware-clarity/ng-clarity#1438]
## Describe the bug

Datagrid column filter input, lose focus while typing filter

## How to reproduce

Reproductible on clarity documentation page

![lost_focus](https://github.com/vmware-clarity/ng-clarity/assets/50275484/163773a8-f633-4df5-9d42-8fb737f68b7a)

## Expected behavior

Input field dont lose focus

## Versions

**Clarity version:**

- 16 and higher

**Framework version:**
Angular 17.3.7

**Device:**

- Type: Dell
- OS: Windows
- Browser: Chrome
- Version 125

**Comment by kumart-netapp** [comment]
This is happening when type character filter had some matching records.

**Comment by ArturSobieraj** [comment]
Yes, but is it correct behavior? Continue typing requires another click whats not too convenient.

**Comment by dtsanevmw** [comment]
Fixed and will be available in the next versions.

**Comment by repolevedavaj** [comment]
> Fixed and will be available in the next versions.

Is there already a planned release date?
