### ISSUE TITLE
After update to 17.2.0 clrDgHideableColumn not hiding column headers after initial load

### ISSUE THREAD

**Issue by peterpivarnik** [vmware-clarity/ng-clarity#1441]
## Describe the bug

After update to version 17.2.0 Datagrid headers are always visible after startup or refresh. After changing visibility of columns everything works as expected. But with first load, all columns are visible regardless of initial setup in of clrDgHideableColumn.
Values are displayed as expected, which results in more headers displayed for only few values.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr17-b2wx7h?file=src%2Fapp%2Fapp.component.html

## Expected behavior

Only column headers with default visibility setup to true should be visible

## Versions

**Clarity version:**

- [ ] v17.2.0

**Framework version:**
 Angular 17_

**Device:**

- Type: [e.g. PC]
- OS: [e.g. Linux mint]
- Browser [chrome]
- Version [125.0.6422.141]

**Comment by dtsanevmw** [comment]
Hello, this was already reported and fix was merges #1418 - check the mentioned PRs in the first issue. Thank you!
