### ISSUE TITLE
clr-dg-pagination ignores initial value for clrDgPage

### ISSUE THREAD

**Issue by derkoe** [vmware-clarity/ng-clarity#1466]
## Describe the bug

When you pass in an inital value for `clrDgPage` to `clr-dg-pagination` it gets ignored and "1" will be used. 

We need to set the initial page of the grid to a certain value because we receive the page number from an URL parameter.

## How to reproduce

Here is a Stackblitz project reproducing it: https://stackblitz.com/edit/clarity-light-theme-clr17-1f4jud

1. Open the Stackblitz project
2. See that the current page is set to "5" on the left but the pager shows "1"
3. When you now page forward the page is set to "2"

![image](https://github.com/vmware-clarity/ng-clarity/assets/123199/0394f47e-9398-4178-90e4-e0472fd3d0b8)

## Expected behavior

I would expect that the pager takes the initial value and starts paging from this value.

## Versions

**Clarity version:**

* @clr/angular - 17.2.1
* @clr/ui - -17.2.1
* @cds/core - 6.9.2

**Framework version:**

* @angular/core - 17.3.11

**Device:**

All devices.

## Additional notes

none

**Comment by dtsanevmw** [comment]
Hello,

Thanks for reporting! Order here matters so if you put the `clrDgPageSize` input before the page input it would work. That's happening due to page size being 0 by default and that's setting the page to 1.  We'll log it internally and look forward that being more reactive.

Regards,
Daniel Tsanev

**Comment by derkoe** [comment]
BTW thanks for the workaround - that worked!
