### ISSUE TITLE
Signpost getting closed when the signpost datagrid filter input clicked or custom select filter applied

### ISSUE THREAD

**Issue by Jayavarc** [vmware-clarity/ng-clarity#1476]
## Describe the bug
In Signpost datagrid filter, whenever we are clicking on input or selecting custom filter applied then it's getting closed automatically

## How to reproduce
    
https://stackblitz.com/edit/clarity-dark-theme-clr13-cds6-wgg3em?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
here is my code snippet
please verify the issue in this stackblitz code
![image](https://github.com/user-attachments/assets/491752e1-d953-4962-9ee1-2f9ca7ddf811)
![image](https://github.com/user-attachments/assets/71ef118e-1a0f-48da-96b6-90edf3de606a)

1.  Go to DataGrid table click on any cell 
2.  in the signpost click on filter 
3.  and click on DataGrid filter input
4.  it gets closed automatically

## Expected behavior

Signpost should not get closed automatically after clicking on DataGrid filter input or custom select input, it should allow
user to add filter context or select multiple custom filter context

## Versions

**Clarity version:**

"@cds/core": "^6.12.0",
"@clr/angular": "^16.5.1",
"@clr/ui": "^16.5.1",

**Framework version:**
_ie: Angular 16

**Device:**

All

## Additional notes

none

**Comment by kumart-netapp** [comment]
Can someone look into this?
We are also facing same issue.

**Comment by Jayavarc** [comment]
@Daniel Tsanev can you please look into this issue

**Comment by dtsanevmw** [comment]
Hello,

We don't recommend nesting components in this specific way so we won't be able to look into that at the moment.

Regards,
Daniel Tsanev

**Comment by kumart-netapp** [comment]
> Hello,
> 
> We don't recommend nesting components in this specific way so we won't be able to look into that at the moment.
> 
> Regards, Daniel Tsanev

Sorry, I don't see any such guideline/restrict in documentation of Clarity.

**Comment by valentin-mladenov** [comment]
@kumart-netapp and @Jayavarc if you search similar behaviour you can use modal as an alternative.

https://clarity.design/documentation/modal
