### ISSUE TITLE
Datagrid detail pane does not open after page change

### ISSUE THREAD

**Issue by ArturSobieraj** [vmware-clarity/ng-clarity#1484]
## Describe the bug

If opening details of the first record in a datagrid is set, after changing the page, details are closed. After next page change, they are again open. 

## How to reproduce

https://stackblitz.com/edit/stackblitz-starters-izur2e?file=src%2Fapp%2Fapp.component.html

![detail_pane_next_page_bug](https://github.com/user-attachments/assets/85649325-3379-4e96-83e6-c37262e0d6bd)

## Expected behavior

After page change, details of the first record are always open

## Versions

**Clarity version:**

"@cds/core": "6.10.0"
"@clr/angular": "17.2.1"
"@clr/ui": "17.2.1"

**Framework version:**
"@angular/core": "17.3.7"

**Device:**

- Type: Dell
- OS: Windows
- Browser Chrome
- Version 126.0.6478.127

## Additional notes

If there is problem with dependency installation, you should use npm install --force and than start the project again.

**Comment by valentin-mladenov** [comment]
Hello @ArturSobieraj ,

In your `recordPageChanged` method you should give more time for the datagrid to recalculate the new page's rows and columns. 
`1` ms is enough in your example.

````
  recordPageChanged(page: number) {
    const newIndex = this.pageSize * (page - 1);
    setTimeout(() => {
      this.selectedRecord = this.gridData[newIndex];
    }, 1);
  }


```

**Comment by kevinbuhmann** [comment]
Valentine is correct. However, note that the detail pane is not designed to stay open after a page change. See https://clarity.design/documentation/datagrid/code/detail-pane.

**Comment by jokarmus** [comment]
I'm curious why it works for odd pages and for even it doesn't.

**Comment by kevinbuhmann** [comment]
It works for all pages of you adjust the code as Valentin suggested. Otherwise, you get weird behavior due to timing issues.
