### ISSUE TITLE
Datagrid column width calculation applying to wrong column when using expanded row

### ISSUE THREAD

**Issue by oznu** [vmware-clarity/ng-clarity#1487]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support space in Google Chat to raise Clarity issues._**

## Describe the bug

When using the Datagrid with expandable rows, the `width` applied to each column is the width for the column to it's left when using expandable rows (specifically with `*clrIfExpanded`)

eg.

|   |  col 1 | col 2   | col 3   | col 4   |
|---|---|---|---|---|
| >  | has width of expand toggle??  | has width of col 1   | has width of col 2   | has width of col 3   |
| >  |   |   |   |   |
| > |   |   |   |   |

## How to reproduce

Issue is easily reproduced and shown here:

https://stackblitz.com/edit/clarity-dark-theme-clr17-wdd6fj?file=src%2Fapp%2Fapp.component.html

<img width="1069" alt="image" src="https://github.com/user-attachments/assets/f4921304-4c51-4e98-b27f-b8fc5c51bf4a">

## Versions

**Clarity version:**

- [x] v17.2.1

**Framework version:**

Angular 17

**Device:**

- Type: macOS
- OS: macOS
- Browser: Edge
- Version: Latest

## Additional notes

This issue was not present in 17.1.0.

**Comment by kumart-netapp** [comment]
We are also seeing this issue with latest 16.x version update

**Comment by dtsanevmw** [comment]
Fixed in [a51d2d8](https://github.com/vmware-clarity/ng-clarity/commit/a51d2d86e5296311b781c48a1c59ec0245775258) and it will be in the next release
