### ISSUE TITLE
Cannot find module 'lit-html'

### ISSUE THREAD

**Issue by husains53** [vmware-clarity/ng-clarity#150]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug
Error: node_modules/@cds/core/button-action/button-action.element.d.ts:43:22 - error TS2307: Cannot find module 'lit-html' or its corresponding type declarations.

43     render(): import("lit-html").TemplateResult<1>;
                        ~~~~~~~~~~


Error: node_modules/@cds/core/icon/icon.element.d.ts:94:32 - error TS2307: Cannot find module 'lit-html' or its corresponding type declarations.

94     protected render(): import("lit-html").TemplateResult<1> | import("lit-html").TemplateResult<2>;
                                  ~~~~~~~~~~

Error: node_modules/@cds/core/icon/icon.element.d.ts:94:71 - error TS2307: Cannot find module 'lit-html' or its corresponding type declarations.

94     protected render(): import("lit-html").TemplateResult<1> | import("lit-html").TemplateResult<2>;
                                                                         ~~~~~~~~~~


Error: node_modules/@cds/core/internal/base/focus-trap.base.d.ts:12:32 - error TS2307: Cannot find module 'lit-html' or its corresponding type declarations.

12     protected render(): import("lit-html").TemplateResult<1>;
                                  ~~~~~~~~~~

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

Angular: 14.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.7.3

**Clarity version:**
    "@cds/core": "^6.0.1",
    "@clr/angular": "^13.3.2",
    "@clr/icons": "^13.0.2",
    "@clr/ui": "^13.3.2",
- [ ] v12.x
- [ ] v13.x
- [ ] Other:

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by husains53** [comment]
Solve it Using Command -> `npm i lit-html`

**Comment by bbogdanov** [comment]
Hi @husains53 

I will take a bet and say that had a previous version of Clarity Core installed in your app. 

`lit-html` is not longer used inside `@cds/core`

Steps to resolve the issue without the `lit-html` with `@cds/core@6.0.0`:
- Remove `node_modules` folder
- Remove `package-lock.json` and `yarn-lock.json`
- `npm install` or `yarn install` 
- Issues should be gone.
