### ISSUE TITLE
Datagrid: hiding the last column adds whitespaces at the end and shows scrollbar

### ISSUE THREAD

**Issue by fichtip** [vmware-clarity/ng-clarity#1501]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support space in Google Chat to raise Clarity issues._**

## Describe the bug

Hiding the last column of a datagrid ends up in showing some whitespaces a the end of the datagrid in addition to the scrollbar.

Showing all columns
![grafik](https://github.com/user-attachments/assets/bb8a0b31-579c-4ea3-a246-5f7b62cf5345)

Hiding non-last column
![grafik](https://github.com/user-attachments/assets/f4eee8fa-d806-4c05-a0d2-da8b8bee6392)

Hiding last column
![grafik](https://github.com/user-attachments/assets/fea917b1-1730-4734-8286-709ce3ef34cd)

## How to reproduce

This behavior can also be seen with the provided example in the [documentation](https://clarity.design/documentation/datagrid/code/hide-show).

1.  Open link of documentation from above
2.  Click on 'Manage Column'
3.  unselect 'Favorite color'

## Expected behavior

No whitespaces and no scrollbar when hiding the last element.

## Versions

**Clarity version:**

```
"@cds/core": "^6.12.0",
"@clr/angular": "^17.2.1",
"@clr/ui": "^17.2.1",
```

**Framework version:**

`"@angular/core": "~17.1.2",`

**Device:**

- Type: Lenovo ThinkPad P53
- OS: Windows 11
- Browser Firefox, Edge
- Version FF 128.0.3, Edge 127.0.2651.74 

## Additional notes

_Add any other notes about the problem here._

**Comment by dtsanevmw** [comment]
Fixed in [b4a4935](https://github.com/vmware-clarity/ng-clarity/commit/b4a4935b9103fbb04a1f7944e11872f2eb7f5709) and it will be in the next release.
