### ISSUE TITLE
Upload Button Close event

### ISSUE THREAD

**Issue by princekumar27** [vmware-clarity/ng-clarity#1507]
How can i get the close event of upload button.
Also in formcontrol can i get the file details.

Please provide sample and suggestions. Thanks

**Comment by kevinbuhmann** [comment]
Do you mean the clear button? There is no event specifically for this, but a `change` event will be dispatched on the file `input` element when the selected file is cleared. Also, if you are using a template or reactive form control, you can handle the file being cleared via handling the value changes on the form control.

**Comment by kevinbuhmann** [comment]
>How can i get the close event of upload button.

Do you mean the clear button? There is no event specifically for this, but a `change` event will be dispatched on the file `input` element when the selected file is cleared. Also, if you are using a template or reactive form control, you can handle the file being cleared via handling the value changes on the form control.

>Also in formcontrol can i get the file details.

Yes. The value of the `FormControl` will be the selected `FileList` or `null`.

**Comment by kevinbuhmann** [comment]
> How can i get the close event of upload button.

Do you mean the clear button? There is no event specifically for this, but a `change` event will be dispatched on the file `input` element when the selected file is cleared. Also, if you are using a template or reactive form control, you can handle the file being cleared via handling the value changes on the form control.

> Also in formcontrol can i get the file details.

Yes. The value of the `FormControl` will be the selected `FileList` or `null`.

> Please provide sample and suggestions.

https://clarity.design/documentation/file-picker/code

**Comment by princekumar27** [comment]
Yes Got it. Thanks much. @kevinbuhmann .

**Comment by kevinbuhmann** [comment]
You're welcome!
