### ISSUE TITLE
Stepper rendering problems on Safari

### ISSUE THREAD

**Issue by Jinnie** [vmware-clarity/ng-clarity#152]
## Describe the bug

Changing stepper steps in Safari leads to severe rendering issues.

## How to reproduce

1.  Go to https://angular.clarity.design/documentation/stepper in Safari
2.  Fill in fields
3.  Click "Next" button
4.  See error

![Screen Shot 2022-06-06 at 17 41 26](https://user-images.githubusercontent.com/1798828/172184337-d476e6b2-df5f-447a-9d94-240495b53794.jpg)

## Expected behavior

![Screen Shot 2022-06-06 at 17 41 55](https://user-images.githubusercontent.com/1798828/172184364-c0e5fd05-376f-4a1e-83dd-7ca00b9daf13.jpg)

## Versions

**Clarity version:**

- [ ] v12.x
- [ ] v13.x
- [ ] Other:

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

The error only occurs in Safari on Mac. In Chrome all is okay. Zooming in/out on the screen also fixes the layout.

**Comment by williamernest** [comment]
No issues with my safari 16.2. Maybe it's something local ?
<img width="630" alt="image" src="https://user-images.githubusercontent.com/34519388/219827781-184a4f9f-e4ef-4a01-8c75-5c8902f2cbbe.png">

**Comment by Jinnie** [comment]
I still reproduce it after the upgrade. 
No errors. Just the `counter` related CSS is failing to apply (most probably the `counter-reset` and is messing the elements it attaches to.
I have put this on hold for a while, as it is lower priority one, which escalated. I have a safe fix ready, though, but I'd prefer to have 100% reproduction before I submit a PR for it.
