### ISSUE TITLE
Pagination is not working correctly for server driven Datagrid 

### ISSUE THREAD

**Issue by baggsie** [vmware-clarity/ng-clarity#1526]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

Hi,

When using a server driven Datagrid component the pagination is not correctly rendered :
- There are no pagination controls displayed
- The `pagination.totalItems` is not working correctly (always displays '0')

## How to reproduce

See the stackblitz example from the docs : 
- https://clarity.design/documentation/datagrid/code/server-driven
- [Stackblitz](https://stackblitz.com/run?file=src%2Fapp%2Finventory%2Fvalues.ts,src%2Fapp%2Finventory%2Fuser.ts,src%2Fapp%2Finventory%2Fpokemon.ts,src%2Fapp%2Finventory%2Finventory-items.json,src%2Fapp%2Finventory%2Finventory.ts,src%2Fapp%2Fexample.component.ts,src%2Fapp%2Fexample.component.scss,src%2Fapp%2Fexample.component.html)

## Expected behavior

![image](https://github.com/user-attachments/assets/57c4b0d0-c98c-4dfd-8d97-d29010a9eabe)

## Actual behavior
![image](https://github.com/user-attachments/assets/79ef3cf9-e5bb-4b5b-87f3-b1106005df60)

## Versions

**Clarity version:**

- [ ] v13.x
- [ ] v15.x
- [X] Other: 17

**Framework version:**
Angular 16 (Stackblitz)

**Device:**

- Type: Thinkpad
- OS: Ubuntu
- Browser Chrome
- Version 127

**Comment by Rebolon** [comment]
Hello baggsie,
To my mind, you have to specify manually the input [clrDgTotalItems].
So when the server return you the total items, you send it to the ClrDgPagination, and then the paginator will work finely.

**Comment by baggsie** [comment]
Thanks @Rebolon ;)

**Comment by LynxDelli** [comment]
The bug is just in the stackblitz sample - thanks for noticing it 
https://stackblitz.com/edit/b3hxvn?file=src%2Fapp%2Fexample.component.html Will be updated.
