### ISSUE TITLE
Cannot attach [clrLoading] directive to buttons

### ISSUE THREAD

**Issue by conradbekondo** [vmware-clarity/ng-clarity#1532]
## Describe the bug

The `clrLoading` directive cannot be found according to the screenshot below even after using `ClrButtonModule` and `ClrLoadingButtonModule` modules

![image](https://github.com/user-attachments/assets/0adcd2fc-7a56-43ed-9702-236efe501518)

## How to reproduce

1. Install `@clr/angular`v17.2.1 and `@clr/ui`v17.2.1 with Angular 18 
2. Add `ClrButtonModule` and `ClrLoadingButtonModule` modules to the `AppComponent`.
3. In the template declare a button tag and try to bind a valid value to the `[clrLoading]` directive on the button.

## Expected behavior
The code should compile with the template having the `[clrLoading]` directive in use.

## Versions

**Clarity version:**

- [ ] v13.x
- [ ] v15.x
- [x] Other:

**Framework version:** 17.2.1

**Device:**

- Type: DELL
- OS: Windows: [WSL Ubuntu]
- Browser: chrome
- Version: 124

**Comment by kevinbuhmann** [comment]
You need the `ClrLoadingModule` as well. Sorry, the module structure for some things is confusing.

**Comment by conradbekondo** [comment]
@kevinbuhmann thanks so much. That cleared things up
