### ISSUE TITLE
Datagrid select all and filter icons are misaligned with the header text when a header cell wraps on multiple lines

### ISSUE THREAD

**Issue by d3lio** [vmware-clarity/ng-clarity#156]
## Describe the bug

Have a datagrid with multiple selection, a column with sort and filter and another column with a long header text (to span multiple lines). Then the select all checkbox and the filter icon remain to the top of the cells but the text and the sort icon are centered vertically.

![Screenshot 2022-06-07 at 17 00 52](https://user-images.githubusercontent.com/6381604/172401073-e9400878-6c7d-45b9-8c59-91b34fb46499.png)

## How to reproduce

See the description. Can also be reproduced by editing the examples in the documentation to have more header text through the dev tools.

## Expected behavior

I would expect they are either all centered or all aligned top.

## Versions

**Clarity version:**

- [x] v12.x
- [x] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12, 13

**Device:**

Any

**Comment by lil-kim** [comment]
![header content alignment](https://user-images.githubusercontent.com/23196444/179630032-363d9eca-bd35-4611-afd8-cd80666e3609.png)
The icons and checkbox within the header should be vertically center aligned with the text.
