### ISSUE TITLE
Input loses focus under a clr-tree-node

### ISSUE THREAD

**Issue by filipeferreira-dev** [vmware-clarity/ng-clarity#1576]
## Describe the bug
The `inputs` inside a `clr-tree-node` component are losing focus when you click on them.
It happens every time time.

![Untitled video (1)](https://github.com/user-attachments/assets/4046f8f5-a8b2-4951-ab03-c349c29a6196)

## How to reproduce

[Link to a reproduction scenario](https://stackblitz.com/edit/clarity-light-theme-clr17-sq58ke?file=src%2Fapp%2Fapp.component.html)

1.  Click on input `Try to click here`
2.  See it losing the focus on the tree-node

## Expected behavior

input keeps the focus.
## Versions

**Clarity version:**
- [x] v17.0.1

**Framework version:**
Angular 17.1.2

**Device:**

- Type: Notebook
- OS: Windows 11
- Browser: Chrome
- Version: Version 129.0.6668.70 (Official Build) (64-bit)

## Additional notes

As I saw, it is being caused by the method `focusTreeNode()` in the  [tree-node.ts](https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/data/tree-view/tree-node.ts) file.
The method checks if the target element `document.activeElement` is the tree node. If it is not, they move the focus to the node.
It could check if it is not an element that the user can enter data before changing the focus.

**Comment by valentin-mladenov** [comment]
Hello @filipeferreira-dev ,

`clr-tree` and `clr-tree-node` doesn't support nested interactive elements such as inputs, because of accessibility reasons.

`A tree view is a hierarchical component that shows the visual representation of the parent-child relationship between the branch nodes.`

**Comment by filipeferreira-dev** [comment]
Thanks for the clarification!
