### ISSUE TITLE
Datagrid: How do one get currently displayed datagrid columns?

### ISSUE THREAD

**Issue by MTstomachTM** [vmware-clarity/ng-clarity#1588]
## Describe the bug(?)

`ClrDatagridColumn` gained from `ClrDatagrid.columns` does not have `hidden` property in Clarity v17.
Reading previous Clarity version issue suggest that I can use the `hidden` property in `ClrDatagridColumn`.
I assume the `clrDgHiddenChange` event no longer used since there was a mention emitting that event would be too 'noisy'. I tried hooking a method to this event, but it never emitting.
How do one get currently displayed/hidden datagrid columns?

## How to reproduce

1.  Get reference to the datagrid component using `@ViewChild(ClrDatagrid) datagrid!: ClrDatagrid`
2.  Get registered datagrid columns from `this.datagrid.columns`
3.  Intellisense for `ClrDatagridColumn` does not show `hidden` property

## Expected behavior

Is there any other way to get `ClrDatagridColumn` hidden state?

## Versions

**Clarity version:**

- [ ] v13.x
- [ ] v15.x
- [x] Other: v17.3.1

**Framework version:**
Angular 18.2.3

**Device:**

- Type: Laptop
- OS: Windows 11
- Browser: Edge
- Version: 129.0.2792.79

**Comment by kevinbuhmann** [comment]
Does this example help? https://stackblitz.com/edit/clarity-light-theme-clr17-yua7jo?file=package.json

Basically, you can listen to `clrDgHiddenChange` events and update some local state.

**Comment by kevinbuhmann** [comment]
> I assume the `clrDgHiddenChange` event no longer used since there was a mention emitting that event would be too 'noisy'. I tried hooking a method to this event, but it never emitting.

That event does work. You can bind to `clrDgHiddenChange` events and update some local state. Example: https://stackblitz.com/edit/clarity-light-theme-clr17-yua7jo?file=package.json

**Comment by MTstomachTM** [comment]
Right. Thank you @kevinbuhmann for the example.

Apparently because I was using `<ng-container *clrDgHideableColumn>` instead of `ng-template`.
