### ISSUE TITLE
Icons in navigation links have wrong color

### ISSUE THREAD

**Issue by repolevedavaj** [vmware-clarity/ng-clarity#1602]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support space in Google Chat to raise Clarity issues._**

## Describe the bug

In #1554, the icon color has been set to the link color, but in case of links in a navigation, a different color applies (`--clr-nav-link-active-color`). Therefore the icons get now styled with a wrong color: 
![image](https://github.com/user-attachments/assets/9d9330a7-99c3-4f95-b1bb-691f3969e8a1)

## Expected behavior

Icons in navigation links should keep color `--clr-nav-link-active-color`.

## Versions

**Clarity version:**

v17.3.1

**Comment by kumart-netapp** [comment]
After upgrading to latest version(17.3.1), the vertical nav icon colors are changed to blue if you visit the nav once. It should be grey.

![image](https://github.com/user-attachments/assets/369fbae7-27eb-4101-9aaa-d3ac3aa8a6c1)
In the above image, Normal, Electric is blue as I had visited them at least once. 

Link: https://stackblitz.com/edit/kjoau7?file=package.json

**Comment by valentin-mladenov** [comment]
@repolevedavaj and @kumart-netapp thank you for reporting this find.

We will investigate it in details and come back to you.

**Comment by valentin-mladenov** [comment]
@repolevedavaj and @kumart-netapp fiz for this issue will be available with the next v17 release.
