### ISSUE TITLE
Figma lib link is broken

### ISSUE THREAD

**Issue by leudantas** [vmware-clarity/ng-clarity#1607]
Hello! I’m a product designer and would like to share the Clarity DS with my team for our project. However, the link to the Figma libraries (https://www.figma.com/@vmware) is currently broken.

I searched for the files in the Figma Community but couldn’t find anything. Could someone assist me or share the files? We were really hoping to use this library!

Thank you in advance :)

**Comment by kevinbuhmann** [comment]
Unfortunately, Broadcom disabled all public Figma links, so the public Figma library for Clarity is no longer available. I will work internally to get the website updated.

**Comment by dmaincy** [comment]
> Unfortunately, Broadcom disabled all public Figma links, so the public Figma library for Clarity is no longer available. I will work internally to get the website updated.

Does this mean we won't be able to get Clarity Figma libraries in the future?

**Comment by kevinbuhmann** [comment]
> Does this mean we won't be able to get Clarity Figma libraries in the future?

Currently, the Clarity Figma library is only available internally. I don't know of any plans to change this because we are not able to make Figma libraries publicly-available due to the change in company policy.

**Comment by dmaincy** [comment]
Thank you Kevin for your prompt reply. It is sad to hear that this has changed under the new management. I just hope that all the great work you are doing with Clarity itself will continue to be available to us all.

**Comment by leudantas** [comment]
I'm really sorry to hear that! I was really looking forward to using Clarity DS :( thank you for clarifying and wish you all the best!
