### ISSUE TITLE
Clarity components not recognised in docker container app for angular

### ISSUE THREAD

**Issue by Samorax** [vmware-clarity/ng-clarity#1656]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

**_If you are a VMware employee or a contractor in VMware, please use our support space in Google Chat to raise Clarity issues._**

## Describe the bug

My package.json file gets installed and served properly on my local machine without errors and shows the homepage of the app. When I try containerizing the app using dockerfile and the same package.json as before- I get log errors indicating that the Clarity component is not recognised. Below is a snapshot of the errors.

<img width="739" alt="clarity-angular-docker-bug" src="https://github.com/user-attachments/assets/031cbfb1-597b-4c3a-a2ec-2ebdb86a66a6" />

## How to reproduce
I am unable to use the Clarity Stackblitz template for reproduction of the bug because it does not support docker. I have pasted my package json and dockerfile. Below is a snapshot of both files:

<img width="792" alt="docker-clarity-bug-package json" src="https://github.com/user-attachments/assets/0985783b-b51f-4ca3-8d4d-b8b90755fa3f" />

![Screenshot 2024-12-22 184256](https://github.com/user-attachments/assets/a3d2f55a-b961-4a8a-b33d-1e6b14a71271)

## Expected behavior
The app should load after running the container without any errors from Clarity components.

## Versions
**Clarity version:**
- [ ] v17.x

**Framework version:**
 Angular 17

## Additional notes

_Add any other notes about the problem here._

**Comment by kevinbuhmann** [comment]
Please share a link to a repository with a reproduction, and I'll look into this.

**Comment by Samorax** [comment]
Thanks for getting back @kevinbuhmann .This is the [repo](https://github.com/Samorax/docker-clarity.git). Looking forward to hearing from you.

**Comment by Samorax** [comment]
On a reproduction I discovered where the bug lies. The issue is not with clarity or angular.
