### ISSUE TITLE
datepicker selected day resets to current day of month if user changes month or year

### ISSUE THREAD

**Issue by steve-haar** [vmware-clarity/ng-clarity#179]
When you change the month or year of the datepicker, the selected date resets to the 15 instead of preserving the previously selected date. Currently, there is no workaround for this.

We need to determine what the desired behavior is so we know if this is a bug or not.

https://vmware.slack.com/archives/C0JF8D2LB/p1655204484003639

**Comment by kevinbuhmann** [comment]
I am unable to reproduce this in v16.
