### ISSUE TITLE
clr v12 text style on the clr-alert-warning alerts is different from all other alert styles

### ISSUE THREAD

**Issue by imonikaimonika** [vmware-clarity/ng-clarity#181]
## Describe the bug

As could also be seen on clarity official docs, v12 https://v12.clarity.design/documentation/alerts#examples 
the text color on the clr-alert-warning alerts is different from all other alert styles

## How to reproduce

Add an alert with warning and any other alert to see the difference - do nothing custom. Issue is also visible in docs examples _
https://v12.clarity.design/documentation/alerts#examples  

1.  Just add an alert with warning and observe text style

## Expected behavior

The text style should match all other clr alerts' 

## Versions

**Clarity version:**

- [ X ] v12.x
- [ ] v13.x
- [ ] Other:

**Framework:**

- [ X ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Device:**

- Type:  MacBook 
- OS: iOS
- Browser  chrome
- Version 102.0.5005.61

## Additional notes

as suggested in slack channel, filing this bug

**Comment by ashleyryan** [comment]
@colinreedmiller do you have thoughts on this? Is it darker for accessibility? The warning alert using #333333 and the other alerts use #666666

**Comment by colinreedmiller** [comment]
This is a bug. The text colors have always been the same in all 4 standard alerts. The color should be #565656
Please check with a previous release for confirmation.

**Comment by kevinbuhmann** [comment]
I believe this has been fixed in v16. https://clarity.design/documentation/alert
