### ISSUE TITLE
The date range modal and the input of 'date' are not in line...

### ISSUE THREAD

**Issue by greenthus** [vmware-clarity/ng-clarity#183]
As one navigates to the modal the put in the FROM date...
after filling the from date the TO date can't be sooner then that from Date.
okay no problem, can be arranged and set with the modal click.

however... at that point I can paste in any text (date) and it can differ from the restrictions that are set in the modal section.

expected: they should be in line.

at entering the text date: "pasting a date should be checked against the settings set at the modal" so to speak.

Clarity version:

[ X ] v12.x
 v13.x
 Other:
Framework:

[ X ] Angular
 React
 Vue
 Other:
Framework version:
Angular 12

Device:

OS: Windows
Browser Edge

**Comment by greenthus** [comment]
![image](https://user-images.githubusercontent.com/104067056/174562624-7021846f-8d71-434a-8258-67ce75cf939a.png)

**Comment by ashleyryan** [comment]
Hello, can you please create a working example of the issue you're describing here: https://stackblitz.com/@clr-team/

**Comment by kevinbuhmann** [comment]
We need a Stackblitz reproduction with instructions in order to triage this issue. I cannot determine the issue with given information.

We don't have a "date range modal" component, so I am not sure what exactly this issue is referencing.
