### ISSUE TITLE
clr-alert only works with core icon sets

### ISSUE THREAD

**Issue by Shakiem** [vmware-clarity/ng-clarity#204]
### Discussed in https://github.com/vmware-clarity/ng-clarity/discussions/193

<div type='discussions-op-text'>

<sup>Originally posted by **Shakiem** June 24, 2022</sup>
I just upgraded clr/angular to 13.3.1 from 1.3.9 and I am noticing that the <clr-alert/> component can only load icons from the core icon set with the clrAlertIcon attribute.

Is there some other setup required for this to work with all icons? I had no issues in 1.3.9 using icons from the technology set.

Below shows a test setup where I am displaying two app level alerts, one with an icon from the technology shapes and another with an icon from the core shapes. Only the core shape displays correctly.

![clr-alert-13](https://user-images.githubusercontent.com/7884554/175651232-91c49682-546d-41b8-8302-0da78d008154.png)

</div>

**Comment by kevinbuhmann** [comment]
It appears that you've not properly registered the icon you want to use. Please follow the instructions linked above.

If you have registered the icon or registerinh it doesn't work, feel free to reopen this issue. It would be very helpful to include a reproduction on StackBlitz in that case.

**Comment by kevinbuhmann** [comment]
Yes, because the alert component uses `cds-icon` internally.

**Comment by Shakiem** [comment]
Registering the cds icon before use did work. Thank you!
