### ISSUE TITLE
clr-combobox doesn't support name property while showing examples in the doc with it

### ISSUE THREAD

**Issue by robertIsaac** [vmware-clarity/ng-clarity#226]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

now looking at the doc of [checkbox](https://clarity.design/documentation/combobox#examples) it shows that you can add `name` property to it

while looking at the [source code](https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/forms/combobox/combobox.ts) it doesn't seem there is any input for a name

I'm not sure if the example or the code is wrong
and if it should have a name property, what is it for?

## Expected behavior

for the docs and the code to be consistent

## Versions

**Clarity version:**

- [x] v12.x
- [ ] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Comment by Jinnie** [comment]
The combobox is a custom forms control.
It's implementing the ControlValueAccessor interface, which helps it get registered as a supported, though custom control in the Angular Forms API.
The Angular docs on building custom controls don't require anything to be done client side for handling the name property, and I haven't gone in detail in the Angular code too see how it gets handled. But you can often find the need to supply a `name` together with the need to add `ngModel`, so I can speculate the two might be sharing common code.
So, the short answer is that the Angular Forms subsystem is handling the name attribute, the same way is it does for non-custom controls, like the `input`, `select`, etc.
