### ISSUE TITLE
cds-icon documentation issue

### ISSUE THREAD

**Issue by pelhamrj** [vmware-clarity/ng-clarity#230]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug
It seems the documentation for Icons on the clarity.design site is taking you to the older clr-icons rather than cds-icons.

## How to reproduce

1. Go to https://clarity.design
2. Click on Icons
3. See the old clr-icons documentation

## Expected behavior

I should be able to see the cds-icon documentation instead of the clr-icon documentation.

**Comment by kevinbuhmann** [comment]
We are currently working on updating the icon documentation.

**Comment by kevinbuhmann** [comment]
The https://clarity.design/documentation/icons documentation page has been updated.
