### ISSUE TITLE
SVG Download of Icon 404

### ISSUE THREAD

**Issue by pelhamrj** [vmware-clarity/ng-clarity#231]
### Describe the bug

When downloading the vector suite at https://core.clarity.design/foundation/icons/shapes/, the contents are not up to date with what is displayed. For instance technology/pdf-file is missing from the download.

Additionally, attempting to click on pdf-file or any of the newer 5.0 vectors, and downloading it singularly, it downloads a *.svg file with the contents: 404: Not Found.

### Reproduction steps

```
1. Go to https://core.clarity.design/foundation/icons/shapes/
2. Click Download SVG Icons button
3. Icons are missing.

OR

1. Go to https://core.clarity.design/foundation/icons/shapes/
2. Click "Shapes" tab.
3. Search for any new file since 5.0.0 (i.e. pdf-file)
4. Click on the icon
5. Click on SVG Icon download button.
6. An empty vector is downloaded with the contents: 404 Not Found
```

### Expected behavior

The assets should remain up to date with what is released on the website and when a vector file is downloaded, it should contain the actual data instead of text stating: 404: Not Found

### Additional context

This is for use by our UI/UX team to utilize in Adobe XD/Figma.

**Comment by steve-haar** [comment]
I can confirm this is a bug. We are currently looking into this and will update this issue when it's fixed.

**Comment by kevinbuhmann** [comment]
This should be fixed now. (It was actually fixed several months ago. I just didn't know about this issue.)
