### ISSUE TITLE
disabled input text invisible on safari

### ISSUE THREAD

**Issue by steve-haar** [vmware-clarity/ng-clarity#238]
## Describe the bug

When an input box is disabled with in clrForm > clr-input-container , text in the input box is not shown in Safari browser.
Text is present but not visible.
Find the attached image for issue presentation. Please let me know if there is a workaround for the same or its fixed any update.

## How to reproduce

https://stackblitz.com/edit/clarity-reactive-form-example-kss7i4?file=src%2Fapp%2Fapp.component.html

## Expected behavior

input text should still be visible

## Versions

**Clarity version:**

- [x] v13.x

**Framework:**

- [x] Angular

**Framework version:**
Angular 13

**Comment by dtsanevmw** [comment]
@steve-haar Looks like it's not reproducible anymore so I'm closing it. Please feel free to reopen it and add additional details for reproducing.

**Comment by KingMario** [comment]
Perhaps [the safari bug](https://bugs.webkit.org/show_bug.cgi?id=115510) has been fixed.
