### ISSUE TITLE
Can't compile package with the 13.6.0 ng-clarity version, due to css min function being treated as sass function.

### ISSUE THREAD

**Issue by classicalConditioning** [vmware-clarity/ng-clarity#257]
## Describe the bug

`_combobox.clarity.scss` uses css `min` function, which is getting confused with a sass `min` function which does not accept rem vs % agruments.
Recommended solution is to make sure min is interpreted as a css function at all times - achievable via wrapping it in `calc()` 

## How to reproduce

Update to 13.6.0 and try to build your packages.

## Expected behavior

Should compile.

## Versions

**Clarity version:**

- v13.x

**Framework:**

- Angular

**Framework version:**
Angular 13

**Comment by Jinnie** [comment]
No backport to 12.x is needed. We already have this code there.
Thanks for the issue and contribution, Alex.
