### ISSUE TITLE
Website contribution link and issue submission link resolution

### ISSUE THREAD

**Issue by colinreedmiller** [vmware-clarity/ng-clarity#273]
On this page:

https://clarity.design/documentation/get-started

This link: 

Contributing to Clarity
The Clarity team welcomes contributions from the community. See our [contribution guidelines](https://github.com/vmware/clarity//blob/master/CONTRIBUTING.md) on GitHub.

Resolves to 404

This link:

Reporting an Issue
Ongoing work and feature requests are tracked using [GitHub Issues](https://github.com/vmware/clarity/issues). Please feel free to file an issue.

Resolves to: https://github.com/vmware/clarity/issues (archived rather than current)

**Comment by Jinnie** [comment]
Fixed
https://clarity.design/documentation/get-started

The legal attribution link needed update too.
