### ISSUE TITLE
Buttons "Warning" and "Danger" with exatcly same color

### ISSUE THREAD

**Issue by ecerichter** [vmware-clarity/ng-clarity#275]
## Describe the bug

Buttons with style "Warning" and "Danger" present exatcly same color.
Is this a bug or by design?

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr13-cds6-cqvgpr?file=src/app/app.component.html

Just use buttons like

<button class="btn btn-warning">Warning</button>
<button class="btn btn-danger">Danger</button>

## Expected behavior

Different colours for differente styles...

## Versions

**Clarity version:**

- [ ] v12.x
- [X] v13.x
- [ ] Other:

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

**Device:**

- Type: Any device. Tested with Windows desktops and notebook, Android cell phones and Linux desktops.
- OS: Windows Server 2019, Windows 11, Android 11, 12 and 13. Linux Mint 13.
- Browser: Chrome, MS Edge, Firefox
- Version: latest updates as per 2022-08-11.

**Comment by kevinbuhmann** [comment]
@colinreedmiller: Thoughts?

**Comment by colinreedmiller** [comment]
This was designed this way.
