### ISSUE TITLE
<clr-alert> does not honor the clrAlertClosed attribute if the clrAlertClosable is set to false

### ISSUE THREAD

**Issue by Shakiem** [vmware-clarity/ng-clarity#276]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

As of `clr/angular v13` the `<clr-alert>` component does not honor the _clrAlertClosed_ attribute if the _clrAlertClosable_ attribute is set to `false`

This prevents any alert that was open to be closed programmatically via the _clrAlertClosed_ attribute

## How to reproduce

_Stackblitz reproduction:_ ( https://stackblitz.com/edit/clarity-dark-theme-clr13-cds6-aepmqd?file=src/app/app.component.html )

1.  Add a `<clr-alert>` to a page
2.  Set the _clrAlertClosable_ attribute to false
3.  Programmatically set the _clrAlertClosed_ attribute to true 
4.  Observe that the alert remains open. This is the bug.

## Expected behavior

I expect to be able to programmatically close `clr-alerts` via the _clrAlertClosed_ attribute regardless of the state of the _clrAlertClosable_ attribute. Previous versions allowed this behavior.

According to documentation the _clrAlertClosable_ attribute should only control whether the alert can be closed when clicking the close 'x'. 

## Versions

**Clarity version:**

- [ ] v12.x
- [x] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

**Device:**

- Type: [Dell Laptop]
- OS: [Windows 10]
- Browser [chrome]
- Version [103.0.5060.134]

**Comment by kevinbuhmann** [comment]
This seems to be by design. If `[clrAlertClosable]="false"`, it makes sense to me that `[clrAlertClosed]="true"` would have no effect as the alert is not closable. Any other behavior would not make sense to me.

I think you should use `*ngIf` to remove the non-closable alert when needed.

**Comment by kevinbuhmann** [comment]
It looks like this behavior was changed in v13. https://github.com/vmware-clarity/ng-clarity/commit/1e29a0e5b51295ea98b1b78fe008a66a111754e3

I'm going to leave this issue closed though because this behavior makes sense. Why should a non-closable alert allow itself to be closed? Allowing that seems in past versions seems like a mistake to me.

Using `*ngIf` should solve you use case.

I'm sorry if I am missing something. Please feel free to add more information if needed.

**Comment by Shakiem** [comment]
I could see your point of view/reasoning; but I disagree with this not being a bug though. The use case that the old functionality facilitates is when the banners/alerts are used to signify a current state of a system. In this scenario the alert should not be dismissible by the user, but more so when the state changes.

The entire point of the `clrAlertClosed` attribute is to facilitate us programmatically controlling the display of the alert. If the intent is for this to be controlled by `*ngIf` then the `clrAlertClosed` attribute is useless and redundant.

I believe the true intent of the attributes (and the documentation indicates this as well) is that:

- `clrAlertClosed` attribute is to be used control the open/closed state of the alert.
- `clrAlertClosable` attribute is to be used to control whether a user can close an alert via the 'x' close button of the alert. Think of it more like a 'user dismissible' state (Can a user dismiss this alert). 

Please review this philosophy with your team as I truly believe it is a legitimate bug. If not then the documentation needs to be updated and I would even recommend removing the `clrAlertClosed` attribute altogether as is it useless in this case. 

https://clarity.design/documentation/alerts/

**Comment by Shakiem** [comment]
@kevinbuhmann any update on this issue? This was a breaking change to the `clr-alert` component as well.

**Comment by kevinbuhmann** [comment]
There is no update at this time. I still believe the previous behavior wasn't intended. A non-closable alert not responding to being closed is consistent behavior, and in my view, correct.

**Comment by kevinbuhmann** [comment]
Regarding, `clrAlertClosed` being useless redundant, I don't think that's true because it supports syntax like `[(clrAlertClosed)]="alertClosed"` if you need to use that state elsewhere, etc.

**Comment by Shakiem** [comment]
@kevinbuhmann Well this change was a **breaking change** that was not documented. We will have to update all references in our app now to compensate for the new behavior, as would all users of the component in previous versions.

If you all are not going to do anything about this issue, at the very least the documentation should be updated. The description of the properties does not adequately describe the current functionality.

**Comment by kevinbuhmann** [comment]
I'm sorry for this issue. I realize we accidentally broke your use case in v13.0.0.

I am at a conference this week. Next week, I will discuss with other members of my team about reintroducing the 12.x behavior or updating the website to reflect the current behavior more explicitly. Reintroducing the 12.x behavior is tricky because it could be viewed as a breaking change requiring a major version bump.
