### ISSUE TITLE
Enhance more/all icons to support badges/warning

### ISSUE THREAD

**Issue by d-m-s** [vmware-clarity/ng-clarity#288]
## Summary

Currently only a few icons support the display of badges or warnings.
Why shouldn't the rest of the icons also support this nice feature? Was there an intention?

- see https://clarity.design/icons/how-to-use
- see https://clarity.design/icons

<img width="350" alt="2022-08-19_15h24_01" src="https://user-images.githubusercontent.com/311619/185630796-e3cc4598-701e-4743-9112-c91ee2c13b0b.png">

In the following an example that is currently not working (€ with badge):
<img width="350" alt="2022-08-19_15h14_44" src="https://user-images.githubusercontent.com/311619/185631785-aa34e551-5703-4f03-be60-c072ac15e3fe.png">

**What is the change?**
All icons support badges and warnings
```
<clr-icon shape="any-icon" class="has-alert"></clr-icon>
<clr-icon shape="any-icon" class="has-badge"></clr-icon>
<clr-icon shape="any-icon" class="has-badge--success"></clr-icon>
<clr-icon shape="any-icon" class="is-solid has-alert"></clr-icon>
<clr-icon shape="any-icon" class="is-solid has-badge"></clr-icon>
<clr-icon shape="any-icon" class="is-solid has-badge--success"></clr-icon>

```
**Why should it go in Clarity?**
base functionality of design-system, consistent implementation of the feature.

**Does this change impact existing behaviors? If so how?**
no

**If this change introduces a new behavior, is this behavior accessible?**
No new behavior, accessibility is given.

## Use case
Our current usecase is an indication regarding the status of an an invoice:
- invoice **open**: 
could be €-icon (neutral, black)
- invoice **fully paid**: 
could be €-icon with success-badge
- invoice **partly paid**: 
could be €-icon with warning-badge
- invoice **overdue**: 
could be €-icon with warning-badge (red icon)

This is just one example, there have been several other usecases identified, where badges would be helpful!

## Implementation plan

If development can not be done by Clarity team any time soon, Porsche Informatik can support and provide a pull-request, just get in touch and outline the desired implementation affordances so we can maximise efficiency and speed of implementation!

**Comment by scroniser** [comment]
@colinreedmiller - this relates to what we discussed yesterday re: color alone. Suggestion: Octagon paired with red while the rest remain the same (circle paired with green, triangle paired with warning). 

FYI, @AmyLiNow

**Comment by colinreedmiller** [comment]
I agree with @Santina - we need refrain from creating badges that convey status with color alone. Adding a green badge without regard to shape complicates the set. Most common currently are yellow / triangle, and red / circle. In both cases the user can differentiate the shape without reference to the color. If this €-icon request is to move forward it must be in reference to a larger view of how badging is done on all icons such that the shape makes sense wherever it is used.
As far as what the actual shapes are I defer to @lil-kim with a few comments:

- I am not sure octagon works for a couple of reasons (can look too similar to a circle especially when focus is not perfect / not universal (internationally).
- We need to look at cases where all 3 statuses are available before we can assess this request. 
- It may make sense to design a new shape for success such as a check mark.

**Comment by lil-kim** [comment]
@d-m-s 
I just wanted to add...
The dot and triangle icons were originally designed to be simple notifications. We only applied them to icons that would likely use a notification badge. With a lot of the icons, it simply didn’t make sense. There is also the critical issue of the file size for the library. In short, we have to be judicious in what icons get added to the library and which ones get badges.

As for adding new shapes: At such a small size, adding any new shapes would make each badge harder to distinguish from one to another. These icons also need to scale down to 50% size, which makes things even more difficult. For these reasons, we have no plan to add new badge shapes or add badges to all icons at this time.

**Comment by d-m-s** [comment]
Thanks for the answers. Of course i can understand the argumentation, but I think that the problems, which currently prevent the rather small enhancement, should be fixed. 

Of course there should be some guidance in the usage of icons, to be able to distinguish them, they need a certain size.
**In general I think it's a loss for clarity, if tickets that really want to improve the design system a simply dropped and closed.**

Why is the icon-lib so fast at its limits when badges are added? 
There should be a way to solve this somehow?
