### ISSUE TITLE
Not able to install clarity in Angular 12 project after going through documentation

### ISSUE THREAD

**Issue by Abhi-Codes** [vmware-clarity/ng-clarity#303]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

I am starting with using Clarity on Angular project . When following the steps mentioned in documentation , I am getting error. 

## How to reproduce

npm install @cds/core @clr/icons @clr/angular @clr/ui --save

```
 npm install @cds/core @clr/icons @clr/angular @clr/ui --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxx-ui@0.0.0
npm ERR! Found: @angular/common@12.2.16
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"12.2.16" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"13 || 14" from @clr/angular@13.8.1
npm ERR! node_modules/@clr/angular
npm ERR!   @clr/angular@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

My package.json
```
"dependencies": {
    "@angular/animations": "12.2.16",
    "@angular/common": "12.2.16",
    "@angular/compiler": "12.2.16",
    "@angular/core": "12.2.16",
    "@angular/forms": "12.2.16",
    "@angular/platform-browser": "12.2.16",
    "@angular/platform-browser-dynamic": "12.2.16",
    "@angular/router": "12.2.16",
    "@ng-idle/core": "^11.1.0",
    "@ng-idle/keepalive": "^11.0.3",
    "moment": "^2.29.3",
    "ng2-pdf-viewer": "^9.0.0",
    "ngx-moment": "^6.0.2",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "tslint-angular": "^3.0.3",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.2.17",
    "@angular/cli": "12.2.17",
    "@angular/compiler-cli": "12.2.16",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.20.51",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "4.3.5"
  }
```

## Expected behavior

Clarity should be installed. 

## Versions

**Clarity version:**

- [ ] v12.x
- [ ] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12.2.16
Node.JS v14.19.0
Npm 8.18.0

**Device:**

- Type:  MacBook

## Additional notes

Is there a documentation for compatibility matrix of Angular and Clarity versions. I am not able to find it.

**Comment by kevinbuhmann** [comment]
Please try installing v12 of the @clr/* packages. The latest packages won't work with Angular 12.

**Comment by kevinbuhmann** [comment]
This is a peer dependency error.

The latest `@clr/*` packages won't work with Angular 12. You need to 1) update to Angular 13 or 13 or 2) use v12.x of the `@clr/*` packages and v5.x of the `@cds/*` packages.

I'm going to close this issue, but feel free to comment if the above doesn't help.
