### ISSUE TITLE
Upgrade to Angular 14

### ISSUE THREAD

**Issue by kevinmerckx** [vmware-clarity/ng-clarity#304]
First of all, great UI library and thanks for making that available to the community.

It would be nice to have `@clr/angular` upgraded to Angular 14 to solve compatibility issues returned by NPM when installing. It works for now, I can force the install.

Thanks!

**Comment by kevinbuhmann** [comment]
We widen the peer dependency a few versions back on 13.x. Have you tried the latest version?
