### ISSUE TITLE
ClrControlContainer component use wrong icon color

### ISSUE THREAD

**Issue by rbirkgit** [vmware-clarity/ng-clarity#305]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

ClrControlContainer component use wrong icon color. This is because it sets the icon status to "danger" which overrides the css for forms invalid color. Other container components don't set the status and why they work and use correct red color.

## How to reproduce

Use the clr-control-container component as described here:
https://clarity.design/documentation/forms#:~:text=Custom%20and%20non%2DClarity%20Controls

## Expected behavior

Error icon should have the same red color as the form invalid red, i.e. same red as the input control underline red.

## Versions

**Clarity version:**

- [ ] v12.x
- [x] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

## Additional notes

Here is part of the source code of it. As you can see it adds the status. That line should be removed. See the clr-input-container as example as that one works.

```
@Component({
  selector: 'clr-control-container',
  template: `
        ...
        <cds-icon
          *ngIf="showInvalid"
          class="clr-validate-icon"
          status="danger"
          shape="exclamation-circle"
          aria-hidden="true"
        ></cds-icon>
```

**Comment by ashleyryan** [comment]
CAn you please provide a stackblitz so we can see the visual discrepancies

**Comment by rbirkgit** [comment]
Here is what it looks like by default:
![image](https://user-images.githubusercontent.com/6342391/188736175-c0780731-e69d-4636-ab8a-61c8db56f739.png)

This is what it should be:
![image](https://user-images.githubusercontent.com/6342391/188736327-c9359b50-4a6b-49df-a58c-e982b74f7a5f.png)

**Comment by rbirkgit** [comment]
Here you can see how the danger status overrides the correct color:
![image](https://user-images.githubusercontent.com/6342391/188736612-ee6b02e8-c2a7-4fd9-bcae-4c7afe51d50b.png)

**Comment by kevinbuhmann** [comment]
That's not overriding the color of the icon. That's just setting the `--color` CSS variable.
