### ISSUE TITLE
Nested Popovers Issues

### ISSUE THREAD

**Issue by ashleyryan** [vmware-clarity/ng-clarity#314]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

When there is a popover component in a modal (or datagrid detail pane), clicking escape closes the modal instead of just closing the popover element (datepicker, dropdown, popover, etc).

## How to reproduce

https://stackblitz.com/edit/pattern-stacked-esc

1.  Click the >> button on a row to open the detail pane
2.  Click on the dropdown to open the popover element
3.  Click escape and notice the detail panel closes

## Expected behavior

Only the top most popover element should close. ToggleService should stop propagation of the event. This would be a breaking change

## Versions

**Clarity version:**

- [x] v12.x
- [x] v13.x

## Additional notes

Workaround: create a directive to stop the propagation: https://stackblitz.com/edit/pattern-modal-prevent-escape-demo?file=src%2Fapp%2Fapp.component.ts

Relates to VPAT-735, VPAT-12217, VPAT-12247,

Related Issue: https://github.com/vmware/clarity/issues/4610

**Comment by kevinbuhmann** [comment]
This was released in 15.0.0-beta.5.
