### ISSUE TITLE
Responsive Navigation broken when screen width is between 769 and 991 pixels

### ISSUE THREAD

**Issue by jdh148** [vmware-clarity/ng-clarity#335]
## Describe the bug

When using clr-nav-level and the screen width is between 769 and 991 pixels, the nav bar disappears after clicking a link but the  hamburger and overflow icons do not appear. If you resize the screen again within that range, the nav bar reappears until you click a link again. At 768 and below, the hamburger/overflow icons appear correctly when the nav bar is hidden. At 992 and above the nav bar correctly remains visible without the icons. 

## How to reproduce

Stackblitz template is here: https://stackblitz.com/edit/clarity-light-theme-clr13-cds6-mfdtpe?file=src%2Fapp%2Fapp.component.html

1.  While view the page, resize screen width to between 769 and 991 (or in dev tools, set it to the screen size of an iPad Air or Surface Pro 7 or other tablet.) Navbar will be visible.
2. Click any of the links in the nav bar. The nav bar will hide, but the hamburger (and overflow, if clr level 2 is used) do not appear.

## Expected behavior

While the screen width is between 769 and 991, hide the nav bar and make the hamburger and overflow icons visible.

## Versions

**Clarity version:**

- [ ] v12.x
- [X] v13.x
- [ ] Other:

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 14

**Device:**

Desktop PC, Windows 11, Edge and Chrome 106

## Additional notes

None

**Comment by kevinbuhmann** [comment]
I fixed this in #328. It will be the next release.
