### ISSUE TITLE
So much css

### ISSUE THREAD

**Issue by esoubiran-aneo** [vmware-clarity/ng-clarity#359]
Hello here,

I can understand why there is so much css? And I discover that you put the fond in base64 in css? Is there any way to reduce this?

![image](https://user-images.githubusercontent.com/103997512/197715814-65fb833b-e03d-467d-aab7-1dcba86c9cdf.png)

**Comment by kevinbuhmann** [comment]
You can set `$clr-fontSkipBase64: false` before importing the Clarity styles to skip the base64 inlined font face. You will need to load the Metropolis font another way in that case.
