### ISSUE TITLE
Spinners are invisible

### ISSUE THREAD

**Issue by jerone** [vmware-clarity/ng-clarity#362]
## Describe the bug

Spinners are not visible anymore after upgrading to Clarity 13.
Same thing happens on your website: https://clarity.design/documentation/spinners
It does however work on your storybook: https://358--storybook-clarity-design.netlify.app/?path=/story/spinner-spinner--default

![image](https://user-images.githubusercontent.com/55841/198555157-0a45774b-282c-4199-a2a6-73daddef52fb.png)

## How to reproduce

1.  Go to https://clarity.design/documentation/spinners

## Expected behavior

Working spinners.

## Versions

**Clarity version:**

* @cds/core 6.1.6
* @clr/angular 13.9.0
* @clr/icons 13.0.2
* @clr/ui 13.9.0

**Framework:**

- ✅ Angular v14

**Device:**

- Type: N/A
- OS: Windows
- Browser: Chrome, Edge, Firefox
- Version: latest

## Additional notes

Dark-mode spinner are working.

**Comment by Jinnie** [comment]
It seems at some point we changed using hex colors with hsl colors, during the generation of the spinner icons.
But we've not removed the leading `#` character. And the `#hsl(.....` color does not get recognized.
![Screen Shot 2022-11-21 at 10 40 25](https://user-images.githubusercontent.com/1798828/203004647-d29f445d-5062-4bf8-9f4c-409e06d4b775.jpg)
