### ISSUE TITLE
Disabled radio button issue

### ISSUE THREAD

**Issue by eoincro** [vmware-clarity/ng-clarity#371]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

After upgrading to the latest  version of clarity (13.9.0). 
Disabling a checked radio button does not appear to have clarity styling as it did in previous version.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr13-cds6-p7yjfd?file=src%2Fapp%2Fapp.component.html

disable a checked radio button and it appears like this 
![image](https://user-images.githubusercontent.com/13860204/199267841-db8a73b9-c636-4e80-b9ce-3d19bf53db0d.png)

## Expected behavior

For the disabled checked radio button to appear like this 

![image](https://user-images.githubusercontent.com/13860204/199267584-8c4d0247-6513-4391-9976-f5a659bba7e5.png)

## Versions

**Clarity version:**

- [ ] v12.x
- [x ] v13.x
- [ ] Other:

**Framework:**

- [ x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13.3.11

**Device:**

- Type: Dell xps15
- OS: Windows 10
- Browser Chrome
- Version 107.0.5304.88

**Comment by kevinbuhmann** [comment]
Which version of Clarity is the "expected" screenshot from?

**Comment by kevinbuhmann** [comment]
I confirmed this with our Clarity design team. The current radio styles are correct.
