### ISSUE TITLE
[Datagrid] The dropdown in clr-dg-page-size is missing a label

### ISSUE THREAD

**Issue by deyanovae** [vmware-clarity/ng-clarity#375]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

The select element in clr-dg-page-size does not have an associated label or ARIA label.
http://vtaas.eng.vmware.com:9003/document/accessibility/guideline/select_missing_label.html

## How to reproduce

1.   Go to https://clarity.design/documentation/datagrid/detail-pane.
2.  Scroll down to the full example with Selection and the Detail Pane.
3.  Check the datagrid footer.
4.  The select element in clr-dg-page-size is missing a label.

## Expected behavior

The select elements must provide descriptive text about their function. 

## Versions

**Clarity version:**

- [ ] v12.x
- [ ] v13.x

**Framework:**

- [ ] Angular

**Framework version:**
Angular 12, 13

**Device:**

- Type: [e.g. MacBook]

**Comment by kevinbuhmann** [comment]
The label text is projected by the application. We added the ability for applications to associate that text with the page size `select` element by providing am input to specify the control's ID. So an `aria-label` isn't necessary.

The examples on the website aren't update, but I will fix that now.

**Comment by deyanovae** [comment]
Thank you for looking at this!

I just verified with the WAVE tool and it seems that adding an id doesn't fix the problem.
Please, see the screenshot.

![select_missing_label](https://user-images.githubusercontent.com/117344526/199746290-f6d37961-24ef-4176-836e-e7fcf23e9757.png)

**Comment by kevinbuhmann** [comment]
We need to associate the "users per page" text with the `select` control via a `label` element. That's why I said I am fixing the website now.

This is what I am changing it to fix it:

```html
<clr-dg-page-size #clrDgPageSize [clrPageSizeOptions]="[10,20,50,100]">
  <label [for]="clrDgPageSize.pageSizeOptionsId">Users per page</label>
</clr-dg-page-size>
```
