### ISSUE TITLE
[Datagrid] Empty form label in single selection datagrids

### ISSUE THREAD

**Issue by deyanovae** [vmware-clarity/ng-clarity#377]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

All radio labels for selection radios are empty:
http://vtaas.eng.vmware.com:9003/document/accessibility/guideline/label_empty.html

1.  Go to https://clarity.design/documentation/datagrid/selection-single.
2.  Scroll down to the first example.
3.  Check the label inside clr-radio-wrapper.
4.  It is empty.

## Expected behavior

Ensure that the form label contains text that describes the function of the associated form control.

## Versions

**Clarity version:**

- [ ] v12.x
- [ ] v13.x

**Framework:**

- [ ] Angular

**Framework version:**
Angular 12, 13

**Device:**

- Type: [e.g. MacBook]

**Comment by Jinnie** [comment]
The "Basic Radio Button" scenario (https://clarity.design/documentation/radio) used for these radios automatically creates a wrapper and associated empty label.
We could try using a CSS version of the Clarity radio only instead.

**Comment by williamernest** [comment]
Closed. Resolved in #627
