### ISSUE TITLE
13.9.1 Controls regression causing side effect in Angular 14 reactive forms validation

### ISSUE THREAD

**Issue by krnhotwings** [vmware-clarity/ng-clarity#385]
## Describe the bug

When using clarity forms and controls on Angular 14 reactive forms,

Clarity `13.9.1` is when this issue was introduced, presumably related to issue #337 

## How to reproduce

1.  https://stackblitz.com/edit/clarity-light-theme-clr13-cds6-phchdr?file=package.json
2.  Click the input field
3.  Deselect the input field (no validation triggered)
4.  Click the input field again
5. Deselect the input field again (validation now triggered)

## Expected behavior

When user focuses on input and then defocuses/blurs the input, validation should be triggered immediately.

There are currently two workarounds:

1. Change `@clr/angular` to `13.9.0` (bug introduced in `13.9.1`)
2. Change module imports such that `ReactiveFormsModule` is imported before `ClarityModule`

## Versions

**Clarity version:**

`>=13.9.1`

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular `14.2.10`

**Device:**

- Type: PC
- OS: Fedora 36
- Browser: Firefox, Chromium
- Version: 106.0.1, 107.0.5304.87

**Comment by Jinnie** [comment]
Thanks for the reproduction. It helps a lot.
This is one of probably a series of issues, related to some Angular changes, after which the order of imports started to affect the order in which some updates happen on our side. It theory, this should not be happening, but now the `touched` state gets updated after the NG control emits the validation state change.
What we can do is to delay the state evaluation a bit in our code, so we are sure that touched state is effectively changed.
I'll submit a PR later today.
