### ISSUE TITLE
chore: Support for Angular 15

### ISSUE THREAD

**Issue by pdaigle** [vmware-clarity/ng-clarity#392]
Angular 15.0.0 was released. Will need to branch to start working on Clarity v15 to support Angular 15.

**Comment by kevinbuhmann** [comment]
[I forgot to mention this in https://github.com/vmware-clarity/ng-clarity/releases/tag/v15.0.0-beta.1](https://github.com/vmware-clarity/ng-clarity/releases/tag/v15.0.0-beta.1)

**Comment by architTech** [comment]
what are the supported version of @clr/ui,@clr/icons,@cds/core with clarity v15.0.0-beta.1 and Angular15 ?

**Comment by kevinbuhmann** [comment]
- `@clr/ui`: This package released in tandem with `@clr/angular`. You should always be using the same version of both packages.
- `@clr/icons`: This package is deprecated and no longer supported or released. Please migrate to `cds-icon`. https://core.clarity.design/foundation/icons/
- `@cds/core`: The peer dependency for `@cds/core` is currently the same as before: `^5.6.0 || ^6.0.0`.
