### ISSUE TITLE
ClrVerticalNavGroup caret should not be visible without children

### ISSUE THREAD

**Issue by 15937823** [vmware-clarity/ng-clarity#396]
It is recommended to add controllable down arrow (left arrow) to clr vertical nav group component.

For example:
<cds-icon
      *ngIf="hasChildren"
      shape="angle"
      class="nav-group-trigger-icon"
      [attr.direction]="expanded ? 'down' : 'right'"
      [attr.title]="expanded ? commonStrings.keys.collapse : commonStrings.keys.expand"
    ></cds-icon>

**Comment by Jinnie** [comment]
I do not understand this request.
The groups in vertical nav do have associated caret icons.
Please provide more detailed information.

**Comment by 15937823** [comment]
I dynamically load this navigation data, but when there is no sub navigation under the first level navigation, this icon will still be displayed. It doesn't make sense.

for example:

![image](https://user-images.githubusercontent.com/6398445/202996596-6b016ed8-e16c-4073-819c-a3b07e14cc57.png)


There is no data under Home, but the icon is still displayed

**Comment by Jinnie** [comment]
Thanks, makes sense now. I updated the title.
We will need comment form UX if we can work on this, or there is a usability reason to keep the caret even without children. Otherwise it might be hard to distinguish between group node and actionable node.

cc: @Partick @colinreedmiller

**Comment by kevinbuhmann** [comment]
You shouldn't have a vertical nav group with zero children. I think this is simply incorrect usage of the vertical nav.

**Comment by 15937823** [comment]
> You shouldn't have a vertical nav group with zero children. I think this is simply incorrect usage of the vertical nav.

No, the menu without children is normal. The menu data source API filters permissions.

**Comment by kevinbuhmann** [comment]
>No, the menu without children is normal.

I'm saying the vertical nav is not designed to have groups with zero children.

A nav group with zero children doesn't make sense. Clicking a nav group expands it, but if it has no children, nothing will happen.

>The menu data source API filters permissions.

I think you hide the nav group entirely if the user doesn't have permission for any of the children.

**Comment by kevinbuhmann** [comment]
>No, the menu without children is normal.

I'm saying the vertical nav is not designed to have groups with zero children.

A nav group with zero children doesn't make sense. Clicking a nav group expands it, but if it has no children, nothing will happen. As I stated above, this is simply incorrect usage of the vertical nav.

>The menu data source API filters permissions.

I think you should hide the nav group entirely if the user doesn't have permission for any of the children.

**Comment by kevinbuhmann** [comment]
I am going to close this as resolved as explained above.
