### ISSUE TITLE
Additions to the Clarity Travel icon set

### ISSUE THREAD

**Issue by Stela-Stamenkova** [vmware-clarity/ng-clarity#443]
Hi, please add these icons to the travel set whenever you see fit: https://www.figma.com/file/XPDArdkICmAkUeCXCYaplS/Clarity-Icons-3.0.0?node-id=0%3A5876&t=bLGfEkMty8G3giNZ-0

Thanks in advance!

**Comment by Jinnie** [comment]
Done. Will be available in next release.

**Comment by kevinbuhmann** [comment]
:tada: This issue is resolved in version 6.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/vmware-clarity/core/releases/tag/v6.4.0)
- `v6.4.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
