### ISSUE TITLE
"Unselect All" button for Data Grid columns selector

### ISSUE THREAD

**Issue by ilyabakharev** [vmware-clarity/ng-clarity#465]
### Discussed in https://github.com/vmware-clarity/ng-clarity/discussions/464

<div type='discussions-op-text'>

<sup>Originally posted by **ilyabakharev** January 11, 2023</sup>
Add the "Unselect All" button that will remove all the columns from the Data Grid

![image](https://user-images.githubusercontent.com/1030919/211919166-3c406721-40f4-4848-8c97-60fba371eaa9.png)
</div>

**Comment by kevinbuhmann** [comment]
I am closing this in favor of the discussion thread. We don't need two parallel discussions. We can reopen this or open a new issue if changes are decided. But we cannot technically add an "unselect all" here because at least one column must be selected/displayed.
