### ISSUE TITLE
Validation Regression from #385

### ISSUE THREAD

**Issue by andrew-landsverk-win** [vmware-clarity/ng-clarity#470]
## Describe the bug

I believe there is a regression in the latest version of clarity (v13.11.2 and v15.0.0-beta.4) for the issue I mention in the title (#385). When I roll back to 13.7.0 all of my validation works the way it's expected, however when I try to upgrade past to either the v13 branch or the v15 branch I experience the exact same issue as in #385.

## How to reproduce

I am struggling to reproduce this on stackblitz, much like the original linked issue and PR, but I'm willing to help with the issue in any way that I can.

## Expected behavior

`clr-control-error` shows immediately instead of after navigating to another input and then it showing up.

## Versions

**Clarity version:**

- [ X] v13.x
- [ X] v15.x
- [ ] Other:

**Framework version:**
Angular 15

**Device:**

- Type: Windows Laptop
- OS: Windows 10 22H2
- Browser: Chrome
- Version: 109

**Comment by andrew-landsverk-win** [comment]
@Jinnie thanks for the reply! I will check package.lock and node-modules folders this morning. As a follow up, what is the correct order for the imports?

**Comment by Jinnie** [comment]
> ReactiveFormsModule is imported before ClarityModule

It should not matter, but it was detected that it does, after some version of Angular. We've been trying to fix it on our side, as it's annoying on bigger projects with many subprojects, but still, making sure the order is as above, looks like a stable workaround.

**Comment by Jinnie** [comment]
The changes from v13.14 should further lead to simplified and more stable validation experience:
https://github.com/vmware-clarity/ng-clarity/releases/tag/v13.14.0
I'll close this, please reopen or create new if you still experience problem with versions newer than 13.14.

**Comment by andrew-landsverk-win** [comment]
@Jinnie thank you for the follow up, I will put this on my list to test in the coming week. Thanks!

**Comment by Jinnie** [comment]
Please, be advised to hold a little while from updating, as we've identified some problems with the fix, related to template-driven forms.

**Comment by Jinnie** [comment]
https://github.com/vmware-clarity/ng-clarity/issues/511 is the related issue.

**Comment by andrew-landsverk-win** [comment]
@Jinnie Thanks for the update on this! I haven't had time on my cycles to get back to attempting my update anyway, so I can continue to hold off.
