### ISSUE TITLE
Placeholder text in dark mode (shim) not passing a11y

### ISSUE THREAD

**Issue by rbirkgit** [vmware-clarity/ng-clarity#502]
## Describe the bug

Placeholder text in dark mode (shim) not passing a11y

## How to reproduce

Input field with placeholder text in dark mode (shim)

## Expected behavior

Better contrast

## Versions

**Clarity version:**

- [x] v13.x
- [x] v15.x
- [ ] Other:

**Framework version:**
_ie: Angular 15_

## Additional notes

![image](https://user-images.githubusercontent.com/6342391/218264321-8e9f988f-d326-49b0-a17c-97c400172ef3.png)

**Comment by Jinnie** [comment]
We need some design input on the desired color
CC: @Partick @colinreedmiller

**Comment by colinreedmiller** [comment]
@Jinnie is the placeholder text here in NG using transparency? All inputs or just this one?

**Comment by Jinnie** [comment]
Only `clr-forms-placeholder-color`, no opacity.
in dark theme currently defined as: $clr-forms-placeholder-color: hsl(203, 16%, 72%);
in shim:   --clr-forms-placeholder-color: var(--cds-global-typography-color-200);

The reported problem is about the shim.

**Comment by williamernest** [comment]
This was resolved in @cds/core@6.3.1. Upgrading your dependencies should resolve the issue. I added a PR to upgrade this project and add a UI snapshot to validate the fix. 

https://github.com/vmware-clarity/core/commit/963987c3a084376718d99f9805812daa38dad35e

**Comment by rbirkgit** [comment]
Thanks! Confirmed with 6.3.1
