### ISSUE TITLE
Shim - Dark mode shows white manage columns button

### ISSUE THREAD

**Issue by rbirkgit** [vmware-clarity/ng-clarity#508]
## Describe the bug

The manage column button in the grid is white in dark mode when using the shim.

## How to reproduce

Use shim and switch to dark mode

## Expected behavior

Dark button 

## Versions

**Clarity version:**

- [x] v13.14.0
- [x] v15.0.0 rc2
- [ ] Other:

**Comment by williamernest** [comment]
Resolved in #514
