### ISSUE TITLE
Basic Datagrid filter is not working

### ISSUE THREAD

**Issue by biziosan** [vmware-clarity/ng-clarity#512]
## Describe the bug

I am trying to add a simple filter to a column in the Datagrid. This is a very simple example that should work right out of the box. However, I am not able to trigger the re-rendering of the table once the filter is applied. 

## How to reproduce

I created a very simple example in: https://stackblitz.com/edit/clarity-with-clr-angular-ui-f2m1on?file=src/app/app.component.ts

1.  Go to the filter icon in the "Color" column.
2.  Click on the checkbox "Violet"

## Expected behavior

The content should be filtered according to the selected color, but it is not.

## Versions

**Clarity version:**

- [X] v13.x
- [ ] v15.x
- [ ] Other:

**Framework version:**
Angular 13

**Device:**

- Browser [chrome, firefox]

## Additional notes

I am sure I am missing a step in the setup of the customer filter. I can't seem to be able to find the source of the problem though.

**Comment by kevinbuhmann** [comment]
Try using the smart iterator, `*clrDgItems`, instead of `*ngFor`. With `*ngFor`, you would need to filter the items in you application logic when the `clrDgRefresh` event is emitted.

**Comment by biziosan** [comment]
Thank you! That did the trick.
