### ISSUE TITLE
Focus on title when modal is open

### ISSUE THREAD

**Issue by jlgarcia-vs** [vmware-clarity/ng-clarity#519]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug
When a modal is open the focus is in title. This looks very strange.

![image](https://user-images.githubusercontent.com/78475380/221405528-fe96acc5-fd5d-46ce-b8db-386f74c29d84.png)

## Versions

**Clarity version:**

- [ ] v13.x
- [X ] v15.0.0
- [ ] Other:

**Framework version:**
Angular 15.2.0

**Device:**

- Type: PC
- OS: Windows 11
- Browser Chrome
- Version 110.0.5481.178

**Comment by kevinbuhmann** [comment]
This is the intended behavior. The reason is so that a screen reader will read the modal title when the modal is opened.

**Comment by Jinnie** [comment]
This is a default behavior. By pure Accessibility standard, it should land on the first actionable item inside the content of the Modal. 
But, as this content is provided by the user, we can't automate it and we're setting it on the Title. If better positioning is needed, then it should be handled by the projected content itself. In some cases, when there are no actionable items on the page for example, there is no need to override the default behavior.
