### ISSUE TITLE
Datagrid `[clrDgSelectable]="false"` shows selection checboxes as disabled, but allows selection in Clarity 15

### ISSUE THREAD

**Issue by ivanovbo** [vmware-clarity/ng-clarity#520]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

If `clrDgItems` is used on the rows to iterate over your data, the selection checkboxes look disabled, but you can click on them and change the checked state.
If `ngFor` is used on the rows to iterate over your data,  the selection checkboxes look enabled, and you can click on them and change the checked state.

## How to reproduce

1.  Go to https://stackblitz.com/edit/clrdgselectable-ng15-bfl95l
2.  Click on any of the data grid selection checkboxes

## Expected behavior

If `[clrDgSelectable]="false"`, then the selection checkboxes should be disabled, and it should not be possible to check/uncheck them on click.

## Versions

**Clarity version:**

- [ ] v13.x
- [x] v15.x
- [ ] Other:

**Framework Version:**
Angular 15

**Device:**

- Type: MacBook
- OS: Mac OS
- Browser chrome
- Version 110

## Additional notes

With `@clr/angular` v13 the behavior is the same if you use `ngFor`, but if `clrDgItems` is used, then `[clrDgSelectable]="false"` works as expected.

**Comment by kevinbuhmann** [comment]
I think this is a regression from #478. I will fix it.

**Comment by kevinbuhmann** [comment]
>With @clr/angular v13 the behavior is the same if you use ngFor

`*ngFor` and `[clrDgSelectable]` don't work together currently. See #157. I have a potential fix but it a breaking change.

For the scope of this issue, I will "ignore" this scenario.

**Comment by kevinbuhmann** [comment]
So this is actually a regression that was introduced in Angular 15. https://github.com/angular/angular/issues/48350#issuecomment-1405900515
