### ISSUE TITLE
[Built-in Filter]Unexpected tooltip over string filter

### ISSUE THREAD

**Issue by AllForNothing** [vmware-clarity/ng-clarity#534]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug
An unexpected tooltip will appear when focusing on a string filter in a datagrid :
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/30999793/222635062-148f54f2-3216-4baf-a4ed-2bc1e972125a.png">

Looks like it's the browser autocomplete functionality, but I'm not sure I've typed `t` and `f ` somewhere.

## How to reproduce

Go to the doc page and select `v15`. For any string filter of a datagrid, click the filter input, an unexpected tooltip will appear

## Expected behavior

The tooltip should not appear. It does not look good and may cause some security issues.

## Versions

**Clarity version:**

V15

**Framework version:**
Angular 15

**Device:**
Chrome 109 on Moc OS

## Additional notes

_Add any other notes about the problem here._

**Comment by williamernest** [comment]
Thanks for the report. This is caused by the autofill functionality on the filter input. Since we use the "search" name, the browser tries to be smart about suggesting other terms you've used on a field with the same name. We'll look into changing the name, and potentially adding an API for users to provide their own

**Comment by kevinbuhmann** [comment]
:tada: This issue was resolved in version 13.15.0 :tada:

The release is available on:
- [GitHub release](https://github.com/vmware-clarity/ng-clarity/releases/tag/v13.15.0)
- `v13.15.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by kevinbuhmann** [comment]
:tada: This issue was resolved in version 15.1.0 :tada:

The release is available on:
- [GitHub release](https://github.com/vmware-clarity/ng-clarity/releases/tag/v15.1.0)
- `v15.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
