### ISSUE TITLE
Certain Clarity Angular components crash Angular Language Service extension

### ISSUE THREAD

**Issue by MTstomachTM** [vmware-clarity/ng-clarity#569]
## Describe the bug

Using `clr-dg-column` or `clr-dropdown` (AFAIK) in component crash the Angular Language Service extension on VS Code.

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1. Generate new Angular project using `npx @angular/cli new my-app`
2. Choose to add Angular route and use SCSS as stylesheet format
3. Get into generated project folder
4. Add Angular CDK using `npx ng add @angular/cdk`
5. Add Clarity Angular using `npm i --save @clr/angular @clr/ui`
6. Add `ClarityModule` to `@NgModule` imports dependencies in `app.module.ts`
7. Replace `app.component.html` content with either
```
<clr-dropdown></clr-dropdown>
````
 or
```
<clr-datagrid>
  <clr-dg-column></clr-dg-column>
</clr-datagrid>
```

## Expected behavior

Angular Language Service should not crash

## Versions

**Clarity version:**

- [ ] v13.x
- [x] v15.0.3
- [ ] Other:

**Framework version:**
Angular 15.2.2

**Device:**

- Type: VS Code v1.76.2 
- OS: Ubuntu WSL2 on Windows 10 Home 22H2 build 19045.2728
- Browser: _irrelevant_

## Additional notes

I'm not sure whether my WSL2 config relevant or not, but here it is.
```
[wsl2]
memory=8GB
processors=2
swap=4GB
```

**Comment by atscott** [comment]
Note that the crash is a language service issue, but there is still a problem here that causes type checking to fail because `StopEscapePropagationDirective` is used in the components but not exported. The Angular compiler isn't able to type check templates that have components using `StopEscapePropagationDirective` because it can't import the directive.

**Comment by snow3461** [comment]
Experiencing the same problem as @MTstomachTM.

I understand its a language service issue (it should not crashed for this). But still a problem if it can't be type checked as @atscott mentioned.
