### ISSUE TITLE
Too much empty space in the table when the user uses pagination in datagrid

### ISSUE THREAD

**Issue by VictorZubr** [vmware-clarity/ng-clarity#571]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug
Too much empty space in the table when the user uses pagination in datagrid.

## How to reproduce

1.  Go to [Pagination](https://clarity.design/documentation/datagrid/pagination) in Clarity Design Documentation.
2.  Scroll down to datagrid paginator.
3.  Select "Users per page": 20
4.  Click Last page button >|
5.  We can see too much empty space in the table
![image](https://user-images.githubusercontent.com/35505401/225622728-e055c8bc-7743-403c-b749-95df448bde63.png)
6. If you select the "Users per page" value even more, then there will be more empty space

## Expected behavior
On the last page, the table should have an auto-height so that there is no empty space

## Versions

**Clarity version:**

- [ ] v13.x
- [x] v15.x
- [ ] Other:

**Framework version:**
_ie: Angular 15_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by williamernest** [comment]
Adjusting the data grid height in this way would cause a visually jarring effect where the data grid and the surrounding content would jump to a smaller size and then jump back when changing the pages. This would also cause the user's cursor to no longer be over the pagination section of the data grid, which could frustrate users. 

You may be able to achieve this by overriding some of the CSS, but I don't anticipate us changing this.

@colinreedmiller Feel free to re-open this issue if this is something you feel we should address or implement.

**Comment by kevinbuhmann** [comment]
The datagrid does automatically adjust it's height to fit by default.

The linked datagrid example, however, sets a static height for the datagrid likely to prevent the content shift Will described.
