### ISSUE TITLE
The Clarity Stackblitz templates don't have Clarity v15 template

### ISSUE THREAD

**Issue by petarbk** [vmware-clarity/ng-clarity#591]
## Describe the bug
[The report bug guide ](https://github.com/vmware-clarity/ng-clarity/blob/main/docs/CONTRIBUTING_ISSUES.md) has a link to [Clarity Stacklitz templates](https://stackblitz.com/@clr-team).

There is no Clarity v15 template in the [Clarity Stacklitz templates](https://stackblitz.com/@clr-team) that can be used to report a bug in Clarity v15.

The last template there is for Clarity v13
![image](https://user-images.githubusercontent.com/27860833/226939278-df0c4e8c-01ed-4fcf-b144-d376ab70d088.png)

## Expected behavior

There should be Clarity v15 template we could use to report bugs in Clarity v15

**Comment by kevinbuhmann** [comment]
v15 templates are now available. https://stackblitz.com/@clr-team/
