### ISSUE TITLE
Labels in tree view are cut off in v15

### ISSUE THREAD

**Issue by AleksandrovaP** [vmware-clarity/ng-clarity#601]
## Describe the bug

If we have a tree view as options for the clarity dropdown, the labels of the tree view's nodes are cut off. The same situation was working as expected with v13. 

## How to reproduce

![Screenshot 2023-03-27 at 14 07 06](https://user-images.githubusercontent.com/37516804/227924687-7bbbc059-d7d9-4cf6-be8d-e33ac2022169.png)

Stackblitz: https://stackblitz.com/edit/clarity-v15-tree-view-cut-off-labels?file=src/app/app.component.html

1.  Have a tree view inside a dropdown
2.  Open the dropdown
3.  Observe that the labels of the tree nodes are cut off to width ~1.6rem

## Expected behavior

_The whole labels should be visible._

## Versions

- [ ] v13.x
- [x] v15.x
- [ ] Other:

**Framework version:**
_Angular 15_

**Comment by rbirkgit** [comment]
Petya had a workaround:

```
.clr-tree-node .clr-tree-node-content-container > .clr-checkbox-wrapper {
  width: auto;
}
```
