### ISSUE TITLE
Forms > Required field - needs design modification to meet A11y requirements

### ISSUE THREAD

**Issue by lil-kim** [vmware-clarity/ng-clarity#623]
## Required field needs an asterisk to denote that it must be filled.

- Currently Clarity recommends marking ONLY optional fields (as optional). All other fields are to be assumed as required. To be A11y (Maya Lin) compliant, the required fields need to be clearly marked with an asterisk with a legend/key at the top of the form. 
- Add this update to documentation in Clarity website.

Visual specs to follow.

**Comment by kevinbuhmann** [comment]
This has been done for a while.
