### ISSUE TITLE
Clr Date Picker - i18n Lvl 2 tootltip issue

### ISSUE THREAD

**Issue by veritas-hs** [vmware-clarity/ng-clarity#624]
## Describe the bug

There is an issue with the tooltip title attribute added to the Clarity Date Picker icon.
The title attribute does not update when a new Loacle is loaded via Angular method registerLocaleData (when handling multiple languages).
The icon renders the title with the default English language.

## How to reproduce

1. Add the Clarity Date Picker to any Angular component.
```html
<clr-date-container>
  <input autocomplete="off" type="date" clrDate />
</clr-date-container>
```
2. Update the Angular application to load a language locale such as French.
3. Hover over the calendar icon.
![image](https://user-images.githubusercontent.com/129851113/229840508-1faa75c3-bba1-4f7f-ac73-e01bfd07e487.png)
![image](https://user-images.githubusercontent.com/129851113/229841111-d4bbcff5-f7d0-4012-9b4d-aed7efe0e508.png)

## Expected behavior

Option 1:
Update the labels used in the icon title to match the current selected locale language.
Ex. French
'Choisissez la date'
'Date de changement, 04/04/2023'

Option 2:
Add an attribute to allow the usage of custom tooltip text for both states 'Choose Date' & 'Change Date'

The preferred option is for Clarity to handle the custom label tooltip for the languages.

## Versions

**Clarity version:**
v15.0.1

**Framework version:**
Angular 15

**Comment by kevinbuhmann** [comment]
Please see https://clarity.design/documentation/internationalization. You can provide translations as needed.

The string you will want to translate for this is `datepickerToggleChangeDateLabel`.

https://github.com/vmware-clarity/ng-clarity/blob/main/projects/angular/src/utils/i18n/common-strings.default.ts#L61
