### ISSUE TITLE
Clarity v13 - support policy & schedule

### ISSUE THREAD

**Issue by shameerahamed** [vmware-clarity/ng-clarity#638]
I was looking at the Clarity v13 support schedule in the page link below. It is stated that support for v13 ends on August 21, 2022, and the Angular & Clarity compatibility status for clarity v13 is LTS. 

There are recent releases for v13 which are after the above mentioned support end date. I greatly appreciate if anyone can help to provide more details on EOS (end-of-support) for v13. is v13 already reached EOS or the support page is no longer updated ? 

Thanks!

Ref Link: [https://clarity.design/documentation/support](url)

**Comment by kevinbuhmann** [comment]
That was a typo. It should say August 21, 2023. I will fix it.
