### ISSUE TITLE
The ClrExpandableAnimation of ClrDatagridRow shows overlapping behaviour in Safari browser.

### ISSUE THREAD

**Issue by Mohan07Chaudhari** [vmware-clarity/ng-clarity#650]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

The ClrExpandableAnimation of ClrDatagridRow shows overlapping behaviour in Safari browser.

## How to reproduce

Please check below sample example on Chrome and Safari to see difference in expand animation behaviour.

https://stackblitz.com/edit/clarity-dg-expand-row-safari?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

Please check below sample example on Chrome and Safari to see difference in expand animation behaviour.

https://stackblitz.com/edit/clarity-dg-expand-row-safari?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

## Expected behavior

The expand Animation should not show overlapping / lagging behaviour in Safari browser. It should work as that of Chrome. 

## Versions

**Clarity version:**

 v13.x Onwards

**Framework version:**
_ie: Angular 14.2

**Device:**

- Type: MacBook Pro
- OS: MacOS 13.3.1
- Browser: Safari
- Version: 16.4

## Additional notes

 This issue has been reported in NSX UI as bug.

**Comment by Mohan07Chaudhari** [comment]
@dtsanevmw FYI...

**Comment by dtsanevmw** [comment]
fixed with #647 and #651 (13.x)
