### ISSUE TITLE
Datagrid "manage column" spacing

### ISSUE THREAD

**Issue by lefkas95** [vmware-clarity/ng-clarity#653]
## Describe the bug

_In the "manage columns" component of **clr-datagrid** the spcing between the single options is too big when using Firefox. When maintaining more than a few columns, then the user has to scroll in the list of options even if there would be enough space, which is not nice. In Chrome, on the other hand, it looks good._
Firefox:
![image](https://user-images.githubusercontent.com/38698639/233950725-b39b9582-6193-46e4-af6f-fb088dfbd859.png)

With the following CSS rule I managed to fix it and I saw that the same workaround is used in the Clarity documentation:
https://clarity.design/documentation/datagrid/hide-show

`ul.list-unstyled:not([cds-list]) > li { list-style: none; }`

From the Clarity doc: 
![image](https://user-images.githubusercontent.com/38698639/233951624-f15ff8b8-71ad-41a2-983b-e00a3bcd9de8.png)

## How to reproduce

_https://stackblitz.com/edit/clarity-datagrid-manage-column-spacing_

1.  Open view with **clr-dategrid** in it using **Firefox**
2.  Click on 'Manage columns'
3.  See error

## Expected behavior

_Available space is used efficiently just like using Chrome and as shown in the Clarity documentation (but without the need to manually set the list-style property to none): https://clarity.design/documentation/datagrid/hide-show_

## Versions

**Clarity version:**
v15.1

**Framework version:**
_Angular 15_

**Device:**

- Type: all tested devices show same result (laptops, ...)
- OS: Windows 10 & Windows 11
- Browser Firefox 112.0.1 (64-bit)

**Comment by ietabhi** [comment]
Hi,
I am facing same problem when i have less space on top, it will show on bottom. My application is inside iframe and this popover is not visible for customer.

**Comment by pawaru** [comment]
Issue is not reproducible in Clarity v16. Check this [Stackblitz](https://stackblitz.com/edit/clarity-light-theme-clr16-u5hqwh).

Reference screenshot of v16 on Mozilla Firefox: 
![image](https://github.com/vmware-clarity/ng-clarity/assets/137300110/603ddf0d-c7c8-4d6f-871d-a5a1a951a5ef)


CC: @kevinbuhmann

**Comment by kevinbuhmann** [comment]
No further information. This appears fixed.
