### ISSUE TITLE
"expression changed" error with clr-combobox and clr-modal

### ISSUE THREAD

**Issue by sambrow** [vmware-clarity/ng-clarity#663]
## Describe the bug

In certain situations involving clr-combobox and clr-modal, an "expression changed after it was checked" error is reported by angular.

## How to reproduce

1.  Go to https://stackblitz.com/edit/clr-combobox-vs-clr-modal?file=src/app/app.component.html
2.  Wait for the build to complete
3.  Click on the "Open in New Tab" button on the upper-right (link the new window to the project if needed)
4.  In the new tab, turn on the devtools/console window
5. Click the downarrow in the combobox
6. Select the "Pick Me!" choice
7. A modal will appear
8. Click the X in the upper-right of the modal to dismiss it

This error appears in the devtools/console window:

ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

## Expected behavior

Expected no such error to happen.

## Versions

**Clarity version:**

&gt;= 15.0.0

**Framework version:**

Angular 15

**Device:**

- Type: macbook
- OS: OSX
- Browser: Chrome, Firefox, Safari
- Version: latest as of April 28, 2023

## Additional notes

If you move the clr-modal element to be ABOVE the clr-combobox-container element, then this error does not happen.

This did not happen with clarity 13.17.0, we noticed it when moving to 15.x.

**Comment by kevinbuhmann** [comment]
This is related to the modal bug fix in v15 to return focus back to the previously-focused element when the modal is closed. For some reason, there is an issue with a focus binding in the combobox when this happens. I opened a PR that fixes it by simply running change detection on the combobox immediately when it receives focus.
