### ISSUE TITLE
Unable to import symbol StandaloneCdkTrapFocus, PopoverHostDirective

### ISSUE THREAD

**Issue by MTstomachTM** [vmware-clarity/ng-clarity#666]
## Describe the bug

`clr-dropdown` gives error
```
Unable to import symbol StandaloneCdkTrapFocus.
  The symbol is not exported from PATH/node_modules/@clr/angular/index.d.ts (module '@clr/angular').(-993004)
nav-level.d.ts(10, 35): The symbol is declared here.
```
`clr-dg-column` gives error
```
Unable to import symbol PopoverHostDirective.
  The symbol is not exported from PATH/node_modules/@clr/angular/index.d.ts (module '@clr/angular').(-993004)
popover-host.directive.d.ts(2, 43): The symbol is declared here.
```

## How to reproduce

1.  Install `@clr/angular`, `@clr/ui`, and `@angular/cdk@15` on fresh Angular 15 project 
2.  Use `clr-dropdown` or `clr-dg-column` component
3.  Angular Language Service will generate the above error

## Expected behavior

No error should happen

## Versions

**Clarity version:**

- [x] v15.3.0

**Framework version:**
- [x] Angular v15.2.9

**Comment by fergusg** [comment]
I have the PopoverHostDirective issue both _before_ and _after_ recent upgrades to Angular Language Service 16.0.0 (VS Code) and Angular 16.0.0

There are no compile time issues

**Comment by kevinbuhmann** [comment]
We recently exported the popover host directive. I can make an additional change to export the standalone focus trap directive.
