### ISSUE TITLE
Server-Driven Datagrid Selection Bug

### ISSUE THREAD

**Issue by ekrismer** [vmware-clarity/ng-clarity#671]
## Describe the bug

When using multi selection in a server driven datagrid, the checkbox in each row does not match the actual selection.

The bug only occurs for server-driven datagrids using `*ngFor`. Since the server response creates new objects (by reference) with each request, I provided a `trackBy` function to check for equality-by-value.

I was unable to wire up the `[clrDgItemsTrackBy]` input. Not sure if this is mandatory when already using `trackBy` on `*ngFor`.

## How to reproduce

Open [Stackblitz](https://stackblitz.com/edit/clarity-light-theme-clr15-uwfspa?file=src/app/app.component.html)

1. Select the first entry with ID=1
2. Increase the page size from 10 to 25
3. Observe that the checkbox is no longer selected but the selection counter in the datagrid footer is still 1 and the `selected` array still contains the element<br/><img src="https://user-images.githubusercontent.com/8388464/237018806-9d892bd0-8fe3-4ede-9015-0c0cf047a47a.png" height="220px"/>
4. Click select-all checkbox in datagrid header
5. Notice that none of the individual row checkboxes is selected although the selection counter in the footer and the `selected` array show 6 items (Mozart is listed twice)<br/><img src="https://user-images.githubusercontent.com/8388464/237018919-92e2bc25-7fc9-40d3-a408-d8a91d603095.png" height="220px"/>
6. Decrease the page size from 25 to 4
7. Observe that suddenly all visible items have a selected checkbox<br/><img src="https://user-images.githubusercontent.com/8388464/237019058-d4ac37c2-26de-43bf-aaaf-b4287ccd874d.png" height="220px"/>

## Expected behavior

The checkbox in each datagrid row should match the actual selection.

It should not be possible to select an already selected entry again.

## Versions

**Clarity version:**

@clr/angular 15.1.0
@angular/core 15.0.4
@cds/core 6.3.2

**Framework version:**
Angular 15.0.0

**Device:**

- OS: Windows 11
- Browser Firefox 112.0.2

## Additional notes

There seem to be somewhat related issues in the old `vmware-archive/clarity`:

- https://github.com/vmware-archive/clarity/issues/3936
- https://github.com/vmware-archive/clarity/issues/4250
- https://github.com/vmware-archive/clarity/issues/5044
- https://github.com/vmware-archive/clarity/pull/4913

**Comment by kevinbuhmann** [comment]
You need to provide the `[clrDgItemsTrackBy]` datagrid input. Note that this input requires a function with a different signature than `[ngForTrackBy]`. There is no `index` parameter.

**Comment by kevinbuhmann** [comment]
> You need to provide the `[clrDgItemsTrackBy]` datagrid input. Note that this input requires a function with a different signature than `[ngForTrackBy]`. There is no `index` parameter.

See here for a working version: https://stackblitz.com/edit/clarity-light-theme-clr15-t36dcf?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

**Comment by kevinbuhmann** [comment]
You're right. I found the bug and am working on a fix. Sorry!
