### ISSUE TITLE
Unified Content

### ISSUE THREAD

**Issue by cbrittany** [vmware-clarity/ng-clarity#677]
_Please review our [Contribution guide](https://github.com/vmware-clarity/ng-clarity/blob/main/docs/CONTRIBUTING.md) for more details about how to contribute effectively._

## Summary

_Describe the change or feature in detail. Try to answer the following questions._
[see slide deck here](https://miro.com/app/board/uXjVMOuhE-M=/?share_link_id=25983553727)
- What is the change? content (specifically copy) 
- Why should it go in Clarity? because we have inconsistent copy across various experiences w/in VMware
- Does this change impact existing behaviors? If so how? this doesn't change how the back-end would function, it will optimize the overall experience for our end-users
- If this change introduces a new behavior, is this behavior accessible? it will improve accessibility

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_If possible, show examples of the change. You may create one yourself, or link to external sites that have the idea. It can also be very useful to prototype the idea in isolation outside of Clarity with a [Stackblitz example](https://stackblitz.com/@clr-team)._

## API

_Describe the intended API for the feature you want to add. This would include:_

- CSS classes and DOM structure for pure static UI contribution, and inputs/outputs, components, directives, services, or anything that is exported publicly for Angular contributions.
- Examples of code snippets using this new feature.
- Note very clearly if anything **might** be a breaking change.

_In the case of bug fixes or internal changes, there will most likely be no API changes._

## Implementation plan

_Describe how you plan to implement the feature, answering questions among the following or anything else you deem relevant._

- What parts of the code are affected?
- Will you introduce new services, components or directives?
- Can you describe the basic flow of information between classes?
- Does this introduce asynchronous behaviors?
- Will you need to refactor existing Clarity code?
- Will reasonable performance require optimizations?
- Will it need to access native elements (and be incompatible with server-side rendering)?
- ...

## Conclusion

_Describe how long you expect it to take to implement, what help you might need, and any other details that might be helpful. Don't worry, this is obviously non-contractual. 😛_

**Comment by kevinbuhmann** [comment]
What is this issue for? Please full out the template.

**Comment by kevinbuhmann** [comment]
What is this issue for? Please fill out the template.

**Comment by cbrittany** [comment]
Thank you for the question—re: implementation this would be introduction of content-specific guidelines/best practices that will benefit the overall user experience. Code will not be impacted since this is simply introducing best-practices. If there is a specific way you would like the best practice content to be delivered, please let us know so we can post to Clarity.

**Summary addition**
Objective: The CX team is looking to add content guidelines/best-practices to ensure content (words on the screen) are clear, concise, useful, helpful, usable, and accessible (in addition to our existing common components.)

**Use cases for risks due to not implementing recommendation:**
- Grammatical errors and inconsistency result in users lack of trust.
- Unclear, excessive, or sparse copy can quickly lead to confused, frustrated users and process delays.
- Lack of context leads to confused users and/or users being blocked from completing tasks.
- Inaccessible context excludes people by making assumptions on how one navigates a product (ie: relying on visuals to convey information.)
- Direct risk to the business' bottom line - neglected experience, rework w/no benefit, attrition, loss of revenue, wasted hours, lost opportunities, UX/tech debt, and more

**Implementation Plan**
What parts of the code are affected? N/A
Will you introduce new services, components or directives? Yes
Can you describe the basic flow of information between classes? We will leverage the existing classes and correspond to it's relative copy.
Does this introduce asynchronous behaviors? N/A
Will you need to refactor existing Clarity code? No
Will reasonable performance require optimizations? No
Will it need to access native elements (and be incompatible with server-side rendering)? No, not affected

**Conclusion**
For phase one, we will need to better understand how you would like to receive recommended web-writing guidelines/best practices (ie: Miro, Word, PPT, PDF, etc.,) and your help/guidance/expertise to publish on Clarity so that it can be seen across the company and consolidated into one source of truth for recommendations, best practices, and contextual examples for better/more unified voice/tone. You can reach me directly at cbrittany@vmware.com if you need more information/would like to set up a call.

**Comment by williamernest** [comment]
@cbrittany I'll reach out shortly
