### ISSUE TITLE
Close button on clarity datagrid default filter does not clear the input value in the filter.

### ISSUE THREAD

**Issue by DhanashreeSathelkar2020** [vmware-clarity/ng-clarity#694]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug
When user type any value in filter and click on close button the filter pop up is hide. 
How can we clear the filter data on close button. 
Can we have a event emitter to catch this event? 

## How to reproduce
https://clarity.design/documentation/datagrid/built-in-filters
Please check the current filter behavior. Close button in the filter just close the filter pop up, does not clear the content.

1.  Go to datagrid column with filter
2.  Click on filter and type some values
3.  Click on close button, it just close the filter pop up
![image](https://github.com/vmware-clarity/ng-clarity/assets/64770025/f6500893-bbcd-4556-9522-9fda91a00f6b)

## Expected behavior
Please provide an option to clear the content in filter search.
suggestions: 1. close button should clear the content
2. event to capture the close event.
3. clear content option on filter

## Versions

**Clarity version:** 5.2.0

**Framework version:**
Angular 11

**Device:**
Laptop /Desktop

**Comment by kevinbuhmann** [comment]
Clearing the input value would reset the filter making filters basically unusable, though.

**Comment by kevinbuhmann** [comment]
I must be missing something here. Clearing the input value would reset the filter making filters basically unusable.

**Comment by MTstomachTM** [comment]
I agree with @kevinbuhmann. This will affect UX negatively. What if user want to see the value behind the filter dropdown? Clearing the filter value will trigger clrDgRefresh event and change the result shown inside datagrid which defeats the purpose of filtering it.

But if what you mean we need another option to clear the filter value (like another button, for example), I agree. Especially if we need to reset the value for the default filter for number column type.

My current solution: just create a custom filter that fits your need.

**Comment by kevinbuhmann** [comment]
This is not a bug.
