### ISSUE TITLE
Accordion child have wrong CSS when expanded

### ISSUE THREAD

**Issue by ietabhi** [vmware-clarity/ng-clarity#715]
![git-accordion](https://github.com/vmware-clarity/ng-clarity/assets/7829397/dba61125-f0f9-4ea0-923b-31319a084e6e)

## Describe the bug

We have use case when accordion is child of another accordion. level of child is max 5.
when we expand parent node child is collapsed mode but ICON is not showing correctly with expand / collapse mode

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr15-533qyf

https://stackblitz.com/edit/clarity-light-theme-clr15-533qyf

## Expected behavior

We should have clear icon defined with right state of accordion child when expanded and collapsed

## Versions

**Clarity version:**

- [Clarity ] v15.x
- [ Angular] v15.x

**Framework version:**
 Angular 15

**Device:**

- Type: [Windows 11 Laptop]
- OS: [Windows 11]
- Browser [chrome]
- Version [chrome 113 - latest]

## Additional notes

NA

**Comment by ietabhi** [comment]
Anyone looking into this issue?

**Comment by kevinbuhmann** [comment]
I am looking into this now.

**Comment by ietabhi** [comment]
May i know which version/ patch it's available ?
