### ISSUE TITLE
Data grid Hide/Show Columns - get list of hidden/ visible columns

### ISSUE THREAD

**Issue by ietabhi** [vmware-clarity/ng-clarity#753]
## Describe the bug

Hide/Show Columns  - I am looking same feature as we had in angular 13 where i can get list of current hidden column and want to capture event when i will click on hide/ show/ select all

Current behavior  - I will save preferences for user in my database, once user revisit he should not see  hidden column he choose previously.

## How to reproduce
![git-hide-show-column](https://github.com/vmware-clarity/ng-clarity/assets/7829397/f653d8fe-cf94-45ea-91f5-c1bafb42ed1f)

https://stackblitz.com/edit/clarity-light-theme-clr15-po1krs

No way to capture click event

## Expected behavior

I should be able to capture events when i click on popover for show/hide column

## Versions

**Clarity version:**

 v15.x

**Framework version:**
 Angular 15

**Device:**

- Type: Windows Laptop
- OS: Windows 11
- Browser chrome
- Version latest

## Additional notes

NA

**Comment by ietabhi** [comment]
This is will be helpful, thanks for the guidance

**Comment by kevinbuhmann** [comment]
Great! I'm going to close this issue, but if you have any further questions, just comment. Thanks!
