### ISSUE TITLE
DataGrid Batch action row check box is not vertically centered

### ISSUE THREAD

**Issue by kumar-tadepalli** [vmware-clarity/ng-clarity#757]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

DataGrid Batch action row check box is not vertically centered there seems to be some bottom margin/padding.

## How to reproduce
We can see the issue from Clarity doc demos 
https://clarity.design/documentation/datagrid/batch-action
![image](https://github.com/vmware-clarity/ng-clarity/assets/12848838/08ac0d2b-4c33-4469-96f0-3c5b4c86ce6b)

## Expected behavior
DataGrid Batch action row check box should be vertically centered

## Versions

**Clarity version:**

- [ ] v13.x
- [x ] v15.x
- [ ] Other:

**Framework version:**
Angular 15.2.x

**Device:**

- Type: Windows
- OS: Windows 11
- Browser Chrome
- Version 113

## Additional notes

_Add any other notes about the problem here._

**Comment by kevinbuhmann** [comment]
A fix for this is merged. It will be in the next release.
