### ISSUE TITLE
App level alert not rendering properly

### ISSUE THREAD

**Issue by beaker1977** [vmware-clarity/ng-clarity#766]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

Not sure if it's a bug per se but my app level alerts are rending as shown in the attached screenshot. If I have code for just a single alert it spans the full width of the page, However, if I have code to display multiple alerts (lifted from the clarity web site Alerts page) it doesn't span the whole page.

![app alert](https://github.com/vmware-clarity/ng-clarity/assets/27329476/66d2797d-536f-4a7f-aa22-d9cba7a95940)

Here's the problematic code:

<div class="main-container">
	<clr-alerts>
		<clr-alert [clrAlertType]="'info'" [clrAlertAppLevel]="true" [clrAlertClosed]="alertClosed" [clrAlertClosable]="false">
			<clr-alert-item>
			<span class="alert-text">
				This is the first app level alert.
			</span>
		</clr-alert-item>
		</clr-alert>
		<clr-alert [clrAlertType]="'danger'" [clrAlertAppLevel]="true" [clrAlertClosed]="alertClosed" [clrAlertClosable]="false">
			<clr-alert-item>
			<span class="alert-text">
				This is a second app level alert.
			</span>
		</clr-alert-item>
	</clr-alert>
	</clr-alerts>
  <app-header></app-header>
  <app-main>
    <ng-content></ng-content>
  </app-main>
</div>

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**Clarity version:**

- [ ] v13.x
- [X ] v15.5
- [ ] Other:

**Framework version:**
16.0

**Device:**

- Type: Windows
- OS:10
- Browser: Chrome
- Version latest

## Additional notes

_Add any other notes about the problem here._

**Comment by kevinbuhmann** [comment]
Please complete the issue template. We need a StackBlitz reproduction to look into this.

**Comment by pawaru** [comment]
This issue is not seen on Clarity v16. Sample Stackblitz: https://stackblitz.com/edit/clarity-light-theme-clr16-isxnhf

CC: @kevinbuhmann 

![image](https://github.com/vmware-clarity/ng-clarity/assets/137300110/5f993b1f-42ae-41cd-b63f-78bbc158691e)
