### ISSUE TITLE
datagrid-sticky-header is not defined in $clr-layers

### ISSUE THREAD

**Issue by KingMario** [vmware-clarity/ng-clarity#773]
Is it a typo?

refer to: https://github.com/vmware-clarity/ng-clarity/blob/8f610fbd70f2629b83c8ae04a2e78a179f815186/projects/angular/src/data/datagrid/_datagrid.clarity.scss#L682

**Comment by kevinbuhmann** [comment]
I probably should be `datagrid-header-sticky`.
