### ISSUE TITLE
Undocumented visual breaking change after upgrade to v13.15 and v15.1.0 

### ISSUE THREAD

**Issue by gyokkoo** [vmware-clarity/ng-clarity#793]
## Undocumented visual breaking change after upgrade to v13.15 and v15.1.0  
There is a visual breaking change related to the checkbox and radio inputs in Clarity versions 13.15 and 15.1. There has been a significant modification in the pseudo selector used to style these inputs compared to older versions.

In the previous versions of Clarity, the pseudo selector responsible for drawing the checkbox and radio inputs was defined as follows:
`.clr-checkbox-wrapper input[type=checkbox]+label:before`

However, in the latest versions (after 13.15 and 15.1), this pseudo selector has been altered to the following:
`.clr-checkbox-wrapper input[type=checkbox]+.clr-control-label::before`

Link to the breaking change: https://github.com/vmware-clarity/ng-clarity/commit/6f6f1aeba3f3d5ac327c1f0f0ea67ead4d489e34 

This change has resulted in a breaking change that affects our application's visual rendering of checkbox and radio inputs.

To mitigate the impact of the breaking change, this issue requests detailed documentation outlining the change, its implications, and the necessary adjustments required to ensure consistent rendering of the checkbox and radio inputs.

Including this information in the official documentation and release notes would greatly benefit developers who rely on Clarity and help them understand the breaking change and make the required modifications in their applications during the upgrade process. 

## How to reproduce
Here is a demo of the problem that is observed in business-critical applications after the Clarity upgrade to v13.15 from 13.14:

Clarity version v12
A simple example of a working clarity checkbox/radio button:
https://stackblitz.com/edit/clarity-dark-theme-clr12-cds5-pgmgfy?file=src%2Fapp%2Fapp.component.html

```
<div class="clr-checkbox-wrapper">
        <input id="my-checkbox-id" type="checkbox" />
        <label for="my-checkbox-id"> Click me! I am checkbox. </label>
</div>
```

Clarity version v13.15: 
The same HTML structure does not render the checkbox and radio buttons
https://stackblitz.com/edit/clarity-dark-theme-clr13-cds6-sglhg1?file=src%2Fapp%2Fapp.component.html

In order to work, there should be an additional refactoring clr-control-label class to be added to the label
```
<div class="clr-checkbox-wrapper">
        <input id="my-checkbox-id" type="checkbox" />
        <label for="my-checkbox-id" class="clr-control-label"> Click me! I am checkbox. </label>
</div>

```
## Expected behavior

There should be clear documentation in the release notes for this kind of CSS selector changes that might lead to product regressions. 

## Versions

**Clarity version:**
- [X] v13.15
- [x] v15.1.0
- [ ] Other:

**Framework version:**
Angular 13/15

## Note:
According to https://clarity.design/documentation/support this is a breaking change because:
- Any change in visual appearance that's disjoint from the prior implementation.
- Any change causing a loss in functionality from a prior release.

**Comment by kevinbuhmann** [comment]
Your reproduction code snippet may have worked previously, but it doesn't follow our documentation. The plain HTML/CSS code examples in our documentation have (and did have before this change) the required `clr-control-label` CSS class on the label elements.

https://clarity.design/documentation/checkboxes

https://v13.clarity.design/documentation/checkboxes

**Comment by gyokkoo** [comment]
Is it possible to update the release notes to highlight that 'clr-control-label' is now mandatory for labels inside 'clr-checkbox-wrapper' and 'clr-radio-wrapper' in vanilla forms?  

https://github.com/vmware-clarity/ng-clarity/releases/tag/v15.1.0 
https://github.com/vmware-clarity/ng-clarity/releases/tag/v13.15.0 

For bigger applications using Clarity, it is extremely hard to track such selector changes in the upgrade process.

**Comment by kevinbuhmann** [comment]
Yes. We can update the release notes.

**Comment by pawaru** [comment]
Hi @kevinbuhmann checkbox documentation for Clarity v16 is missing the `Code` tab and its examples: https://clarity.design/documentation/checkbox

**Comment by valentin-mladenov** [comment]
@pawaru both release notes are updated.
Regarding missing `code` page/tab, please open separate issue.
