### ISSUE TITLE
Labels are not aligned with the form controls

### ISSUE THREAD

**Issue by rbirkgit** [vmware-clarity/ng-clarity#809]
## Describe the bug

When using forms, the labels are 1px too high compared to other from controls, e.g. input, select etc.

## How to reproduce

https://clarity.design/documentation/forms

![image](https://github.com/vmware-clarity/ng-clarity/assets/6342391/c45d2c14-08d5-44a4-be3c-38857517e05c)

## Expected behavior

Labels being aligned with the text of the form controls

## Versions

**Clarity version:**

- [ ] v13.x
- [x] v15.6.0
- [ ] Other:

**Framework version:**
Angular 15

**Comment by d-m-s** [comment]
furthermore for the demo a meaningful margin between Label and input should be used.
eg. margin-right: 0.5rem;
