### ISSUE TITLE
JS error when using @clr/angular 15.6.0 and angular 15.2.9

### ISSUE THREAD

**Issue by tracylv** [vmware-clarity/ng-clarity#813]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## JS error when using @clr/angular 15.6.0 and angular 15.2.9
When upgrade clarity and Angular:
- Angular to 15.2.9
- @clr/angular to 15.6.0
- @clr/ui to 15.6.0
![image](https://github.com/vmware-clarity/ng-clarity/assets/5001313/ece59986-361d-43b8-a4e6-3f1549c67164)

There is a js error for wizard component
![image](https://github.com/vmware-clarity/ng-clarity/assets/5001313/bed41fbe-5968-4b3d-a590-72e921dadb20)

UT also fail
![image](https://github.com/vmware-clarity/ng-clarity/assets/5001313/a6b583ca-4e8b-4c31-b25a-4551b75d2a3e)

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**Clarity version:**

- [ ] v13.x
- [ ] v15.x
- [ ] Other:

**Framework version:**
_ie: Angular 15_
Angular 15
**Device:**
chrome
- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

Fixed this with downgrade to @clr/angular and @clr/ui to 15.4.0

**Comment by kevinbuhmann** [comment]
Please make sure your wizard pages have a page title. We would need a completed issue template, including a full reproduction, before we can take a look at this.

**Comment by kevinbuhmann** [comment]
Wizards with missing page titles are not supported.
