### ISSUE TITLE
'clr-modal' is not a known element(angular V15, clarity V15.9.0)

### ISSUE THREAD

**Issue by kannaminamahesh** [vmware-clarity/ng-clarity#872]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

upon migrating angular app from V11 to V15 and compiling angular is not recognizing clr compenents like clr-stack, clr-modal, cds-icon, here's the package json.
![image](https://github.com/vmware-clarity/ng-clarity/assets/43477680/e6d26634-4fa9-4f32-91ce-50e60c604a99)

appmodule
![image](https://github.com/vmware-clarity/ng-clarity/assets/43477680/280f9ae6-d4ba-4422-8f64-bad86272777d)

errors

![image](https://github.com/vmware-clarity/ng-clarity/assets/43477680/49d43a91-1420-40d4-8f5b-947a8f71ccb9)

## Expected behavior

compile all the clr components with out errors
## Versions

**Clarity version:**

- [ ] v13.x
- [ x ] v15.x
- [ ] Other:

**Framework version:**
_ie: Angular 15_

**Device:**

- Type: Windows
- Browser: chrome

## Additional notes

_Add any other notes about the problem here._

**Comment by kannaminamahesh** [comment]
can anyone pls help?

**Comment by kevinbuhmann** [comment]
Did you import the `ClrModalModule`? You can also use `ClarityModule`, but you should import the component modules instead of the "everything" module.

**Comment by kevinbuhmann** [comment]
The but template asks for a StackBlitz reproduction. We cannot help until that is added. https://stackblitz.com/@clr-team

**Comment by kevinbuhmann** [comment]
The bug template asks for a StackBlitz reproduction. We cannot help until that is added. https://stackblitz.com/@clr-team

**Comment by kevinbuhmann** [comment]
But here is a guess: Is the error in a lazy-loaded module? If so, you need to import the Clarity component module within the lazy-loaded module, not just the app module.

**Comment by kannaminamahesh** [comment]
We only have one module which is root appmodule.

**Comment by kannaminamahesh** [comment]
do you think clarity, angular version incompatibility causing this? I'm able to install node_modules though.

**Comment by kevinbuhmann** [comment]
ng-clarity v15 works with Angular v15, so no. We will need a full reproduction in StackBlitz to address this further.

**Comment by kannaminamahesh** [comment]
Hi kevin, I'm trying to reproduce the issue in stackblitz, I'm unable to install @cds/core, getting follwing error
![image](https://github.com/vmware-clarity/ng-clarity/assets/43477680/8a518ea9-7e51-4e9b-8e11-a79cc96ebd85)

Here's the stackblitz link
https://stackblitz.com/edit/angular-sqyf2j?file=package.json,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

if possible pls try to show any clarity component(clr-stack clr-modal...) in ui with Angular 15 and clarity version with out any errors so that I can Use the same angular and clarity versions in our project. I tried using stackblitz templates(ang 15 and clarity 15 in local) versions from clarity website by creating a new angular project getting the exact same error that I got with my project

![image](https://github.com/vmware-clarity/ng-clarity/assets/43477680/a6599135-93fb-40c0-9c86-41b045119fdd)

**Comment by williamernest** [comment]
Here's our starter template working correctly with the modal. Use this template to help you investigate why this is broken in your project. I'm closing this as not a Clarity library issue but an issue within the setup of your project. 
https://stackblitz.com/edit/clarity-light-theme-clr15-rxbn4s?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
