### ISSUE TITLE
TypeError initializing ClrAlert

### ISSUE THREAD

**Issue by chris-hardee** [vmware-clarity/ng-clarity#92]
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

A TypeError is generated on initialization of each `clr-alert` components with a `clrAlertClosed` binding to an initially `true` value that are nested within `clr-alerts`. 

## How to reproduce

Stackblitz reproduction: https://stackblitz.com/edit/clarity-light-theme-clr13-cds6-fdb27g?file=src%2Fapp%2Fapp.module.ts

1. Load the stackblitz example page
2. Inspect the console
3. Notice the error:
```
vendor.js:31364 ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at MultiAlertService.close (vendor.js:111464:27)
    at ClrAlert.close (vendor.js:111578:30)
    at ClrAlert.set closed [as closed] (vendor.js:111534:12)
    at setInputsForProperty (vendor.js:35878:35)
    at elementPropertyInternal (vendor.js:34902:9)
    at ɵɵproperty (vendor.js:39345:9)
    at AppComponent_Template (main.js:93:118)
    at executeTemplate (vendor.js:34497:9)
    at refreshView (vendor.js:34363:13)
    at refreshComponent (vendor.js:35554:13)
```

## Expected behavior

The TypeError should not be generated on initialization of a `clr-alert` component with the `clrAlertClosed` binding to an initially `true` value.

## Versions

**Clarity version:**

- [ ] v12.x
- [x] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

**Device:**

- Type: Laptop
- OS: Windows 10
- Browser chrome, firefox
- Version 100.0.4896.127, 99.0.1

## Additional notes

Validation of the array is likely the quick fix, but not triggering the close on initialization seems like the more appropriate fix.

**Comment by kevinbuhmann** [comment]
I have verified that this bug is still present in v16: https://stackblitz.com/edit/clarity-dark-theme-clr16-yedkmu

And I have opened a PR to fix it: https://github.com/vmware-clarity/ng-clarity/pull/1156
