### ISSUE TITLE
chore: angular 14

### ISSUE THREAD

**Issue by coryrylan** [vmware-clarity/ng-clarity#95]
Angular is now cutting v14 releases. To prepare for the 14 release `@clr/angular` will need a `beta` branch to start cutting v14 versions.

- update `@clr/angular` to `@cds/core` and `@cds/angular` v6 latest
- enable the core shim by default in `@clr/angular` this will fix/enable high contrast and other a11y fixes in `@clr/angular`
  - https://beta--core-demo.netlify.app/?path=/story/themes-clarity-ui--page 
- Adjust the focus trap on ClrNavLevel to use the newly provided focus trap from @cds/core v6

**Comment by ShutLee** [comment]
Angular 14 went live a week ago. It's since impossible to add clarity to an up to date project. Any news on this chore?

**Comment by bbogdanov** [comment]
@ShutLee we are investigating if we need to upgrade to v14 or you can use Clarity v13 with Angular v14. So far seems to work fine. 

https://stackblitz.com/edit/clarity-dark-theme-clr13-cds6-yeqqs3

I need to investigate more on example how the bundle size increases but you are able to use Angular 14 and Clarity v13 at the moment.

**Comment by Rebolon** [comment]
ok, so we just have to use npm install instead of ng add and use --force ?

**Comment by jdh148** [comment]
> ok, so we just have to use npm install instead of ng add and use --force ?

Using --force works for me, although I received this error when attempting to build:

`An unhandled exception occurred: Script file node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js does not exist.`

Which I solved with:

`npm install @webcomponents/webcomponentsjs --force`

I'm not sure if manually installing webcomponentjs is a v14 issue or happened in previous versions, but it's not mentioned in the getting started guide.

**Comment by ShutLee** [comment]
for now the solution is to manualy force each package, including webcomponent

the full procedure is here: https://clarity.design/get-started/developing/angular/
The only difference is to force the npm install
> npm install @clr/icons @clr/angular @clr/ui @cds/core @webcomponents/webcomponentsjs --force

**Comment by kevinbuhmann** [comment]
We widened the peer dependency a few versions back on 13.x to allow Angular 14. We don't plan on releasing a v14 of ng-clarity at this time. We are focusing on planning for v15.
