### ISSUE TITLE
Button Group Dropdown not closing automatically for lazily loaded buttons

### ISSUE THREAD

**Issue by poi-schoeninger** [vmware-clarity/ng-clarity#952]
## Describe the bug

We are using Clarity Button Groups together with the [clrInMenu] directive in our project.
In our project, the buttons we want to display are not static, but are loaded dynamically from the backend.
Since the Update to Angular & Clarity 16, the Button Group Dropdown is not closing automatically anymore, when the user clicks a button.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-clr16-c2cgwr?file=src%2Fapp%2Fapp.component.html

1. In section "Lazily loaded buttons:"
2. Wait for 2 seconds until the buttons are loaded
3. Click the 3 dots (...) to open the dropdown
4. Click on "Command 3"
5. The Dropdown is not closing

## Expected behavior

Same Stackblitz as above:

1. In section "Directly initialized property:"
2. Click the 3 dots (...) to open the dropdown
3. Click on "Command 3"
4. The Dropdown is closing as expected

## Versions

**Clarity version:**

- [ ] v13.x
- [x] v15.x
- [x] Other: 16.0.0-beta.2

The problem occurred using the following combinations of Clarity & Angular:

* Clarity 15, Angular 16
* Clarity 16, Angular 16

**Framework version:**
Angular 16.2.5

**Device:**

- Browsers: Chrome, Firefox, Chrome

**Comment by poi-schoeninger** [comment]
Possible Workaround: Get a reference to the ClrButtonGroup using ViewChild and click the menuToggle programmatically:
`
@ViewChild("ClrButtonGroup") readonly clrButtonGroup?: ClrButtonGroup;

// In the method reacting to a button click:
this.clrButtonGroup?.menuToggle.nativeElement.click();
`

**Comment by kevinbuhmann** [comment]
I flagged this as an accessibility issue because the arrow keys don't work for asynchronously-populated menu buttons. We will have a fix soon.
