### ISSUE TITLE
Missing Angular Theming in current docs

### ISSUE THREAD

**Issue by esoubiran-aneo** [vmware-clarity/ng-clarity#96]
## Describe the bug

A part of the documentation is missing.

## How to reproduce

In previous documentation, it was possible to see how to use dark theme using Angular but this section is not in the current docs!

[Previous docs](https://vmware.github.io/clarity/documentation/v0.11/themes#examples)
[Current docs](https://clarity.design/foundation/themes/usage/)

## Versions

**Clarity version:**

- [ ] v12.x
- [x] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Comment by kevinbuhmann** [comment]
This was addressed in our recent website refresh. Please see https://clarity.design/documentation/themes.
