### ISSUE TITLE
Range input handle is below slider on Firefox

### ISSUE THREAD

**Issue by jerone** [vmware-clarity/ng-clarity#973]
## Describe the bug

Range input handle is below slider on Firefox.

![image](https://github.com/vmware-clarity/ng-clarity/assets/55841/99fe5544-6bbe-4d55-bd2f-00d1d75aaf35)

## How to reproduce

Repo 1:
1. Open Firefox
2. Go to https://stackblitz.com/edit/clarity-light-theme-clr16-1i78om?file=src%2Fapp%2Fapp.component.html

Repo 2:
1. Open Firefox
2. Go to documentation website: https://clarity.design/documentation/range/code

## Expected behavior

Same experience as other browsers.

## Versions

**Clarity version:**

- [x] v16

**Framework version:**
Angular 16

**Device:**

- OS: Windows
- Browser: Firefox
- Version: 117

## Additional notes

It looks good on Chrome & Edge.

**Comment by valentin-mladenov** [comment]
Fixed in v16.x and v15.x.
