### ISSUE TITLE
Date picker does not work in a reactive form

### ISSUE THREAD

**Issue by mauritslourens** [vmware-clarity/ng-clarity#975]
## Describe the bug
When the date picker is added to a form and the value is set using `form.patchValue`, 

## How to reproduce

[Example app which shows the issue](https://stackblitz.com/edit/clarity-dark-theme-clr16-kqq3ix)

1.  Both date pickers get an initial date, only the bottom is display the date
2.  Click on the top date picker to change the date
3.  Select a date from the picker that opens up
4.  Nothing happens, the date is not set in the form

## Expected behavior
The form should be updated once the date is selected, like it does in the bottom one.

## Versions

**Clarity version:**

- [ ] v13.x
- [X] v15.x
- [ ] Other:

**Framework version:**
Angular 16

**Device:**

- Type: laptop
- OS: Linux Mint
- Browser Chrome 
- Version 117

## Additional notes

_Add any other notes about the problem here._

**Comment by pawaru** [comment]
Check if this approach helps: https://stackblitz.com/edit/clarity-dark-theme-clr16-o5yc6i

**Comment by mauritslourens** [comment]
that does work, but it looks like a workaround

**Comment by dtsanevmw** [comment]
@mauritslourens the form control is binded to a native input which accepts a string while you patch a Date object -- so the solution provided is accurate and proper use. The issue comes from that patching the date object brakes something in the component and from there you cannot change the value.
